### ISSUE TITLE
Can we reduce the time of writing 

### ISSUE THREAD

**Issue by medaamarnadh** [dtjohnson/xlsx-populate#1]
Hi, 

I am Amarnadh .

I like this module very much .

Now i am trying to write database records to xl sheet . 

I have to write 600 rows in xlsx file and each row contains nearly 33 columns .

So total cells i have to write is 19800 for one sheet which is taking more than 30 seconds .

I have to write more than one sheet some times i have to write nealry  5 sheets like this .
So it will take 150 seconds . 

Is there any optimised way  to use to this plugin.

Because ,I have to write the sheet and have to send it as an attachment in the response in a request

**Comment by medaamarnadh** [comment]
Hello . I am still waiting for the response . Is there any one to respond .

**Comment by dtjohnson** [comment]
Apologies for the delay. Turns out there was a bug in the code creating row nodes that made it impossible for the elementtree module to later find them. So it was creating a new row node each time you called getCell. That scales with a very high order complexity.

The latest v0.0.5 fixes this. I tried populating every cell in a 600x33 workbook and it took about 1s.

**Comment by medaamarnadh** [comment]
Hi johnson .Thank you for the response. I have read the code line by line in the code . I got the solution.
You are actually taking the row every for for getting each cell .This is one reason for the delay .
So what i did is i have take the cell from the row not from the sheet . Now i got the solution for this .

Anyway thank  you for the reply.

**Comment by dtjohnson** [comment]
Glad to hear. FWIW, I just pushed an updated version with some major refactoring that swaps out the XML manipulation modules. The 600x33 example is now only about 300ms.

I'll go ahead and close this issue.

**Comment by eddiecorrigall** [comment]
I'm curious @medaamarnadh, with the new changes, has there been a significant speedup?

**Comment by medaamarnadh** [comment]
Yes. We are getting much speed with those changes when compare to before changes.

**Comment by eddiecorrigall** [comment]
Glad to hear. Thank you very much for your feedback Amarnadh!

**Comment by bhargavi541** [comment]
Hi,

I am also facing some issue with time taken while generating an excel.
I am trying to generate an excel with 210k records with 16 columns and 7 columns, it is taking 39736.125971999ms( 39.73 seconds). How can this time be reduced ?
