### ISSUE TITLE
Formulas with semicolon-separated arguments not working?

### ISSUE THREAD

**Issue by jansiegel** [dtjohnson/xlsx-populate#102]
First of all, awesome library, it gets the job done really painlessly + it's pretty lightweight compared to the alternatives.

I have a problem, though.
When I provide a semicolon-separated arguments to a formula, for example:
```
workbook.sheet(0).cell('C3').formula('SUM(A1;B2)');
```
it doesn't seem to work.

I *think* the formula arguments are usually separated with a comma, but I know that the `;` is also supported (I suppose it's because of a different decimal marks, for example, you won't be able to `SUM` `1,5` and `2,1` using a simple comma)

I've prepared a simple example of this problem: https://jsfiddle.net/0zpb7age/1/

**Comment by dtjohnson** [comment]
The OOXML spec uses commas in formula arguments, not semicolons. Excel supports semicolons if you have a language enabled that uses commas as the decimal separator, but when it store it in the XLSX file it uses commas. Is there a reason you can't use commas?
