### ISSUE TITLE
minification failing for dependency ArgHandler.js through create react app script

### ISSUE THREAD

**Issue by spandzgit** [dtjohnson/xlsx-populate#105]
I'm trying to use xlsx-populate as a dependency with one of my react app. The minification as part of create-react-app script is failing 

Failed to minify the code from this file: 

 	./node_modules/xlsx-populate/lib/ArgHandler.js:9

**Comment by dtjohnson** [comment]
You should probably use the browser bundle in the browser folder instead.

**Comment by mekto** [comment]
I had the same issue, but
```js
import XLSX from 'xlsx-populate/browser/xlsx-populate';
```
does the trick.

**Comment by spandzgit** [comment]
Thanks @dtjohnson @mekto - That solves it. 👍
