### ISSUE TITLE
Browser example not working (e.toLowerCase is not a fuction)

### ISSUE THREAD

**Issue by arielpg** [dtjohnson/xlsx-populate#106]
Hi, i'm trying to use this to export an excel file that needs to have colored cells, and so far i haven't had much luck with other tools, but this one seems promising, so thanks for working on it!

The problem i'm seeing is that your example for browser is currently not working, giving the error e.toLowerCase is not a function, no matter which option i choose.

https://gitcdn.xyz/cdn/dtjohnson/xlsx-populate/beec7cb4ff54d3fb378ed5ad668261a8b30af7f4/examples/browser/index.html

Could you please take a look into it?

**Comment by dtjohnson** [comment]
I'm sure it's just that commit that was failing. You should use a URL with a version number in it:
https://gitcdn.xyz/repo/dtjohnson/xlsx-populate/v1.12.0/examples/browser/index.html
However, GitCDN is returning a [500 error](https://github.com/schme16/gitcdn.xyz/issues/23)...

**Comment by dtjohnson** [comment]
GitCDN is working now and the master and version links are working.

**Comment by arielpg** [comment]
Thanks a lot!
