### ISSUE TITLE
Make parsing support optional

### ISSUE THREAD

**Issue by sylvinus** [dtjohnson/xlsx-populate#107]
Hi!

It would be great to have a flag to disable parsing support. In my usecase we only need to generate XLS files and being able to disable support at the webpack level (with DefinePlugin for instance) would avoid bundling `sax` in our app.

Thanks!

**Comment by dtjohnson** [comment]
`sax` is also used in workbook generation as the lib either reads an existing template or a blank template file that is serialized in the code. It's certainly doable to store the blank parsed workbook instead but I'm not sure it's worth shaving ~20kB from the bundle (or a third of that when gzipped).
