### ISSUE TITLE
Possible to run in Browser

### ISSUE THREAD

**Issue by simonaberry** [dtjohnson/xlsx-populate#11]
Id it possible to run this library in the client browser instead of the nodejs server ?

**Comment by eddiecorrigall** [comment]
Hey @simonaberry,
That would be really awesome. However, as of now xlsx files are read from file. Can you think of a way that this feature can be added? Let me know!

**Comment by dtjohnson** [comment]
Technically, it should be possible with browserify. I haven't used it, but I suspect it would require some effort to make the library support it. All of the dependencies should work. JSZip even has methods for working with HTML5 Blobs.

**Comment by simonaberry** [comment]
I am sure it is possible - because docxtemplater does it perfectly (https://github.com/open-xml-templating/docxtemplater) .... I will see if I can figure out what needs to change, but I must warn you I am no expert, so may end up hacking things .....

**Comment by eddiecorrigall** [comment]
@simonaberry, looks like xlsx-populate is able to run in browser after review our code base. I will get back to you with an example.

**Comment by eddiecorrigall** [comment]
Hi @simonaberry,
I wasn't able to test this yet, but I have a branch "from-url" with the following example:
https://github.com/dtjohnson/xlsx-populate/blob/2b2d6a455bec3719d0adeb24cd9f81346037a968/examples/browserify/index.html

**Comment by simonaberry** [comment]
Thanks, Ill test in in the next few days... but just looking at the code I see that bundle.js requires './utils' ... is that correct ?

**Comment by eddiecorrigall** [comment]
Hi @simonaberry,

I learned enough about browserify to get our library ported to client-side. Checkout the branch "from-url", and run the demo like so:

node ./examples/browserify/

A xlsx file is required to be on the same origin as the host, I had to run an express server to host the demo and the xlsx file. Of course you are free to host a script and an xlsx file your own way. Here is more information on this security model:

https://en.wikipedia.org/wiki/Same-origin_policy

**Comment by simonaberry** [comment]
works brilliantly - thanks !!!!

**Comment by eddiecorrigall** [comment]
Excellent, thanks for the suggestion, its a good addition to our library!

**Comment by eddiecorrigall** [comment]
@dtjohnson,
One of the unit tests is failing for this branch, I'm not sure how it's happening.

`xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"`

This attribute keeps seeping into different tags. Any ideas how? I didn't change much in the library.

**Comment by dtjohnson** [comment]
With v1.0.0, browser support is now a first-class citizen. I'm going to close this issue.
