### ISSUE TITLE
This file is corrupted and cannot be opened

### ISSUE THREAD

**Issue by purell** [dtjohnson/xlsx-populate#111]
Hi,

I'm trying to generate an xlsx file with dynamic columns.

```js
const sheet = workbook.addSheet('test');
for (let col = 0; col < dynamicColumns.length; ++col) {
  const c = that.dynamicColumns[col];
  // sheet.row(0).cell(col).value(c.label);       // Give corrupted file
  sheet.cell(0, col).value(c.label);              // Give corrupted file
}
```

But each attempts give this error `This file is corrupted and cannot be opened` while open it in Microsoft Excel 2016.

Is it because we can't use `[Number]` to specify col,row ? 

If **yes**, how can I convert number to `A1` notation ? Is there a conversion functions ?

If **no**, what I'm doing wrong ? When using this
```js
workbook.sheet(0).cell("A1").value("foo");
```
the file is properly working.

Best regards,

**Comment by purell** [comment]
I finally got it working. This is because row and column are **1-based**.

So
```js
const sheet = workbook.addSheet('test');
for (let col = 0; col < dynamicColumns.length; ++col) {
  const c = that.dynamicColumns[col];
  sheet.cell(0 + 1, col + 1).value(c.label);              // WORK PROPERLY
}
```

But would not be better to issue an **EXCEPTION** when an **INVALID** out of range based is passed ? 0 cannot be used to create a row or a column as they are based-1, so if user pass 0 as column or row, issue an exception please or fix this library to prevent corrupting the output file at least :tongue:

Best regards,

**Comment by purell** [comment]
Also, may I suggest you to expose the class `addressConverter` through the `XlsxPopulate.js` ? This could be **usefull* in some context.

**Comment by dtjohnson** [comment]
Pull requests for both would be most welcome. :)

**Comment by purell** [comment]
Believe me, if I had time I would do it. But I already collaborate on 2 other open source projects and I am a BIG rush at work. However, I will see what I can do ...
