### ISSUE TITLE
Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object

### ISSUE THREAD

**Issue by sidcool1234** [dtjohnson/xlsx-populate#117]
Getting an issue while importing/requiring the xlsx-populate module in the application:

`const xlsxPopulate = require('xlsx-populate');`
or 
`import * as xlsxPopulate from 'xlsx-populate';`

> Uncaught TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object

Node version: 6.0.0
Webpack version: 3.2
xlsx-populate: 1.14.0

**Comment by elhamsarikhani** [comment]
+1

**Comment by dtjohnson** [comment]
If you are running in the browser, import the prebuilt browser version.

**Comment by sidcool1234** [comment]
I am running it with Node.js.

**Comment by dtjohnson** [comment]
Then what are you doing with webpack?

**Comment by duncanmapes** [comment]
I'm having this same issue when I try to use .fromDataAsync
