### ISSUE TITLE
How to enable macros by default and export excel file ?

### ISSUE THREAD

**Issue by hgurung** [dtjohnson/xlsx-populate#122]
I have multiple sheets and want to export excel and reuse it again. But after exporting if i don't enable that excel file macros then its output and formatting is not valid. But if i enable macros and save that file and reuse it then everything works fine. So i want to enable macros by default from the code while exporting excel. 

How to enable macros by default ?

**Comment by dtjohnson** [comment]
I don't think there is a way to make Excel trust a macro-enabled workbook from some setting in the file. That's a security setting. You can save the file in a trusted location or disable your macro security settings. Note that once you trust a workbook once Excel will trust it from that point on.
