### ISSUE TITLE
Browser version fails to load XLSX file if cell contains ">"

### ISSUE THREAD

**Issue by arxcode** [dtjohnson/xlsx-populate#124]
If I try to upload the Excel file [Test_with_greater_than.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1952073/Test_with_greater_than.xlsx) with the in-browser variant of xlsx-populate (e.g. [here](https://gitcdn.xyz/cdn/dtjohnson/xlsx-populate/32921c0b357828cf4c9065c60aa5ab9ad5aefd62/examples/browser/index.html) but also with the latest version available via bower), I receive an error message:

> IQc is not defined

The attached Excel file is a very simple file which just contains a single sheet with a ">" (greater than) sign in the first cell. You get the same result with "<" (less than) and also "&" (ampersand). I have created it with Microsoft Excel for Mac 16.12; however, the same results can also be achieved by using xlsx-populate to write a greater-than sign to a sheet.

I tried in Firefox 59.0.2 and Vivaldi/Chrome, so I think it is not a browser-specific glitch.

Running the debugger, it says the second line of the following the source is to blame:

```
  function parseEntity (parser) {
    var entity = parser.entity
    var entityLC = entity.toLowerCase()
    var num
    var numStr = ''
```

I think this is the same issue as #115, as it also gets the "IQc" error. And in turn I think it is this issue from the sax.js repository:

https://github.com/isaacs/sax-js/issues/223

They say it was a bug in UglifyJS (mishoo/UglifyJS2#2783) and has been fixed there. So maybe it would be sufficient to re-uglify with a newer uglify?

**Comment by dtjohnson** [comment]
Please try with v1.17.0. There is also a non-minified version available now.
