### ISSUE TITLE
Cannot read property 'includes' of undefined error while parsing file with merged cells

### ISSUE THREAD

**Issue by awadekaustubh** [dtjohnson/xlsx-populate#127]
Hello,

Thanks for providing this wonderful library.
I am using this library for generating template based report file.

When the xlsx file is formatted with merged cells, it could not parse the file and give an error 

> Cannot read property 'includes' of undefined

My Code :
```
XlsxPopulate.fromFileAsync(filePath).then(workbook => {
            const usedRange = workbook.sheet(0).usedRange();
            usedRange.cells().forEach(cell => {
                cell.forEach(element => {
                         console.log(element.value());
                      });
            });
```

Can you guide me how to avoid this error and parse the file with such formatting.
The same file can be parsed if the merged cells are unmerged .

Thanks,
Kaustubh

**Comment by dtjohnson** [comment]
Please upload a template with functional code that exhibits the issue.
