### ISSUE TITLE
Format border, color, style

### ISSUE THREAD

**Issue by abelmagana88920** [dtjohnson/xlsx-populate#13]
Is the cell can be formatted? I want to format the cell by its font-color, width, background color

**Comment by dtjohnson** [comment]
Unfortunately, styling through the API is not yet supported. It's on the roadmap but no ETA.

What you could do is style the cells in the template beforehand. Then you can populate the value of the cell with the styling remaining in tact.

**Comment by abelmagana88920** [comment]
this package is awesome but i have problem on styling borders in
xlsx-populate,
