### ISSUE TITLE
Can not execute XlsxPopulate.fromFileAsync('/tmp/sample.xlsx') in AWS lambda

### ISSUE THREAD

**Issue by alowsarwar** [dtjohnson/xlsx-populate#132]
I am working on AWS Lambda (Node 8.x) I am able to create an entirely new xlsx But need to access an existing xlsx from relative path and modify it. How can I make this work in AWS lambda environment `XlsxPopulate.fromFileAsync('/tmp/sample.xlsx')`  I could verify that file exists at /tmp/sample.xlsx but not accesible.

**Comment by dtjohnson** [comment]
What error are you seeing?
