### ISSUE TITLE
Problems with formulated cell value

### ISSUE THREAD

**Issue by tjrhodes** [dtjohnson/xlsx-populate#133]
Hi,

First thanks for this great lib, it's going to help me automate a lot of stuff.

I have come across a problem though, a non formulated cell value is fine like this...

this.penale.cell("E" + rowNumber).value();

where this.penale is a sheet. BUT when I try and get the value from a formulated cell like this

this.penale.cell("AM" + rowNumber).value();

I get null, now, the cells that generate the value in the formula have not been manipulated, so the value should be in the saved excel file right? I'm reading lots of values from the sheet ok until this point. So I can only think it's to do with the formulated value? I guess I can manually do what the cell formula is doing, but I don't think value shoudl be returnign null here?

**Comment by smoke** [comment]
As far as I know, this nor any library that I met is evaluating the formulas in the cells, this is only done once you open the file with a real excel like program.

**Comment by tjrhodes** [comment]
Ah ok, I was under the description of value() in the API docs made me think the value is written to the cell by excel when it gets saved so the value would be available for me to read as long as I was careful about the fact that modifying cells involved in the generation of the value would not modify the value.  Ok my current workaround is to do the calculation in JS that the cell in question performs. If that's the best I can do then that's fine, it's probably more robust. Shoudl possibly update the docs though, to make it clearer that it's not possible, getting null freaked me out :D

**Comment by dtjohnson** [comment]
Yeah, unfortunately, live updates to cell formula values would require a full calculation engine like what is built into Excel. That's not feasible. The `value` methods get you the value that was saved by Excel. Once a workbook is written by xlsx-populate or most libraries the precalculated formula values are cleared.

**Comment by mbrevda** [comment]
https://www.npmjs.com/package/hot-formula-parser seems to work (at least in my limited use case). Wondering if it would be hard to include and silently calculate formula values when `.value()` is called?

**Comment by Akxe** [comment]
@dtjohnson How about we pass a second argument to the formula? This would enable us to fill formula value if we know it (it might be wrong, but it is at least something!)

```ts
// const range;
cell.formula(`SUM(${range.address()})`, range.reduce((total, cell) => total + cell.value(), 0));
```
