### ISSUE TITLE
new Blob() sends InvalidStateError when calling outputAsync

### ISSUE THREAD

**Issue by UMAknow-Patrick** [dtjohnson/xlsx-populate#137]
Hi @dtjohnson,
I found out I needed to change line 636 of Workbook.js from
`if (process.browser && type === "blob") return new Blob([buffer], { type: Workbook.MIME_TYPE });`
to
`if (process.browser && type === "blob") return new Blob([new Uint8Array(buffer)], { type: Workbook.MIME_TYPE });`

in order to have is work with IE11

This is not really an issue anymore for me since I found this solution but that could be useful to others.

Regards,

PS: I'm using xlsx-populate in a create-react-app project so I had to use a transpiled ES5 version of the code.
PPS: forgive me if I was supposed to do something else to post this info (like make a pull request) but I'm not familiar with the process

**Comment by dtjohnson** [comment]
Hmmmmm... the current version works fine for me in IE11: https://gitcdn.xyz/repo/dtjohnson/xlsx-populate/master/examples/browser/index.html
