### ISSUE TITLE
npm install error, fs not found

### ISSUE THREAD

**Issue by wengyifeng-HL** [dtjohnson/xlsx-populate#142]
npm run dev, throw error:
```shell
This dependency was not found:
* fs in ./node_modules/xlsx-populate/lib/Workbook.js
To install it, you can run: npm install --save fs
```
run `npm install --save fs`, Is still an error

**Comment by sandeepk01** [comment]
Please try adding below in your webpack configuration, this problem usually happens when you are running the module on Node server and instead build client only solution.

node: {
    fs: 'empty',
   dns: 'mock',
   path: true,
   url: false
}

Hope this helps.
