### ISSUE TITLE
Copy/Duplicate a workbook not works properly

### ISSUE THREAD

**Issue by kutlaykural** [dtjohnson/xlsx-populate#144]
Copy an excel file without doing anything producing a different file. (which have different size)
Is there any solution keep all styles, metadata or other things to not change. 

There is my code below:

`const XlsxPopulate = require('xlsx-populate');
XlsxPopulate.fromFileAsync("original.xlsx").then(workbook => {
    workbook.toFileAsync("out.xlsx");
});`

thank you...

**Comment by dtjohnson** [comment]
No. xlsx-populate must modify the workbook for a number of technical reasons so the output won't be exactly the same.
