### ISSUE TITLE
Date is not getting populated in correct format

### ISSUE THREAD

**Issue by bhargavi541** [dtjohnson/xlsx-populate#148]
I am trying to create a file with date field but as the format I am mentioning is not in the excel its getting set to custom with the format I have specified, But the date value in the file is not showing up the correct value.

 this.workSheet.row(this.rowNumber).cell(this.columnNumber).value(value).style('numberFormat, 'MM/DD/YYYY')

In the below screenshot we can see that date is not in format of mm/dd/yyyy instead its shown up along with date..

<img width="893" alt="screen shot 2018-07-17 at 6 06 43 pm" src="https://user-images.githubusercontent.com/12166146/42817615-3e692438-89ec-11e8-8871-aec985a2b46f.png">

**Comment by bhargavi541** [comment]
value I am giving is a date - 01/17/2017

**Comment by shahidcodes** [comment]
are you parsing date? You need to use `Date` object to get the format working.
```javascript
var moment = require("moment");

this.workSheet.row(this.rowNumber).cell(this.columnNumber).value(moment(value).toDate()).style('numberFormat, 'MM/DD/YYYY')
````

**Comment by alexsommers7** [comment]
A bit late on this but if anyone needs it, this worked for me

`cell.style('numberFormat', 'mm/dd/yyyy;@');`
