### ISSUE TITLE
Could I parse to `json/[object]`?

### ISSUE THREAD

**Issue by thearabbit** [dtjohnson/xlsx-populate#149]
I have excel file like this
```js
// Sheet1
Column 1,Column 2,Column 3
1-1,1-2,1-3
2-1,2-2,2-3
```
I would like to parse to `Json/[Object]`
```js
[
  {Column 1: 1-1, Column 2: 1-2, Column 3: 1-3},
  {Column 1: 2-1, Column 2: 2-2, Column 3: 2-3},
]
```
Please help me

**Comment by shahidcodes** [comment]
No there's no direct way but you can do it using `row.value()`. It'll return array of cell values. You can then map those to object.
You can also use `sheet.range().value()` to do it. It'll return array[row] of array[cell].
ex.
```javascript

sheet.range(fromRowPosition, 1, toRowPosition, numberOfCells ).value();

// [Array(11), Array(11), Array(11), Array(11), Array(11), Array(11), Array(11)]


```

**Comment by dtjohnson** [comment]
Yep. And you can use something like [lodash](https://lodash.com/) to transform the output.
