### ISSUE TITLE
how do I read cell Value?

### ISSUE THREAD

**Issue by TheJegan** [dtjohnson/xlsx-populate#15]
var Workbook = require('xlsx-populate');
 
// Load the input workbook from file. 
var workbook = Workbook.fromFileSync("./Book1.xlsx");
 
// Modify the workbook. 
workbook.getSheet("Sheet1").getCell("A1")

returns a giant object. how do I get the value of cell A1?

**Comment by dtjohnson** [comment]
Unfortunately the 0.x API doesn't support retrieving a cell's value. I just started work on 1.0, which does include that functionality (as well as lots more), but it'll be a bit before we release it.

**Comment by TheJegan** [comment]
that sucks. Well let me know if there is anything I can do to contribute.

**Comment by dtjohnson** [comment]
I just release v1.0.0 which now supports reading cell values. Here's an example:

```js
const XlsxPopulate = require('xlsx-populate');
XlsxPopulate.fromFileAsync("./Book1.xlsx")
    .then(workbook => {
        const value = workbook.sheet("Sheet1").cell("A1").value();
    })
```
