### ISSUE TITLE
Could I render Excel in Excel Online?

### ISSUE THREAD

**Issue by thearabbit** [dtjohnson/xlsx-populate#151]
Could I render Excel in Excel Online like this (jsreport)

![image](https://user-images.githubusercontent.com/4495160/43351292-1a5bc57c-923a-11e8-8180-db9fce8b6179.png)

**Comment by dtjohnson** [comment]
Any workbook you make with xlsx-populate should work in Excel Online. If you're asking about triggering opening it in Excel Online, that's outside the scope of this package.
