### ISSUE TITLE
Issue while trying to read the style of a Cell

### ISSUE THREAD

**Issue by shradhagautam** [dtjohnson/xlsx-populate#159]
I have a requirement in which i need to check if the cell has particular style .
If so the data needs to be modified before insertion.

I  am able to check the style using  cell.style('style_name') and data insertion seems to be proper.
But some how all the styles like color and formatting of the cells are getting removed after that.
Below is the code snippet:

               let cells = workbook.sheet('Sheet1').find('some_value');
                                    cells.forEach(function (cell) {
                                        if (!cell.formula()) {
                                          if(cell.style('numberFormat') === '0%'){
                                             do_something;
                                          }else{
                                             do_something;
                                          }
                                        }
                                    });

**Comment by dtjohnson** [comment]
Nothing looks obviously wrong. Could you please attach a sample workbook with this issue and full code that reproduces it?
