### ISSUE TITLE
Gridlines in excel

### ISSUE THREAD

**Issue by jaykalai** [dtjohnson/xlsx-populate#162]
How to show and print gridlines in print preview and printout?

**Comment by eddiecorrigall** [comment]
#174

**Comment by eddiecorrigall** [comment]
@jaykalai, new release 1.19.0 now has support for printOptions, which will allow you to toggle gridLines. Please [see docs](https://github.com/dtjohnson/xlsx-populate#print-options) and provide feedback and experience with the new feature.
