### ISSUE TITLE
hyperlink to sheet

### ISSUE THREAD

**Issue by tokbuga** [dtjohnson/xlsx-populate#170]
Is there a way link to existing sheet in same workbook

**Comment by eddiecorrigall** [comment]
Hey thanks for your post, I've put together a pull request based on what you provided, #171.

**Comment by eddiecorrigall** [comment]
@tokbuga a new version 1.18.0 has been pushed, this includes new features for hyperlinks:
- email,
- internal addresses, and
- tooltips

Please give this a try, and provide any feedback.
