### ISSUE TITLE
getting "we found a problem with some content in XXX.xlsx" when opening files with Excel that were created with version 1.19.0; does not happen in version 1.18.0

### ISSUE THREAD

**Issue by nitsanavni** [dtjohnson/xlsx-populate#178]
It doesn't happen for all generated files, only some.
We couldn't yet identify the exact parameters that cause this behavior.

**Comment by LesterLyu** [comment]
Please provide the corrupted excel file.

**Comment by eddiecorrigall** [comment]
@nitsanavni If you could provide an example, I can see what I can do.

**Comment by eddiecorrigall** [comment]
Thank you very much, Ill see what I can do.

**Comment by LesterLyu** [comment]
```xml
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
           xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"
           xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" mc:Ignorable="x14ac"
           xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac">
    <sheetPr/>
    <sheetData/>
    <printOptions/>
    <pageMargins/>
</worksheet>
```
Seems ```<printOptions/>``` and ```<pageMargins/>``` should be removed if empty.

**Comment by eddiecorrigall** [comment]
I'm working on a solution, I will commit soon.

**Comment by eddiecorrigall** [comment]
Thank you @LesterLyu

**Comment by eddiecorrigall** [comment]
@nitsanavni, I am sorry I did a poor job at releasing features pageMargins and printOptions in 1.19.0. Please use 1.18.0 in the meantime.

I have worked hard at patching these features in this release:
https://github.com/dtjohnson/xlsx-populate/pull/186

**Comment by eddiecorrigall** [comment]
New release 1.19.1. Please provide feedback.
@nitsanavni @lerit

**Comment by lerit** [comment]
@eddiecorrigall ,v1.9.1 resolve my problem,thank you!
