### ISSUE TITLE
getting raw data instead of formatted data

### ISSUE THREAD

**Issue by gmkumar08** [dtjohnson/xlsx-populate#184]
I have an excel sheet that displays formatted data in the cells (rounded off to 2 decimals) but when I try to get the data, I do not get the formatted data instead I get the raw data (8 decimal value).

![image](https://user-images.githubusercontent.com/46545923/51618416-495c2400-1f54-11e9-8ac4-bbaf98f02ce9.png)

**Comment by LesterLyu** [comment]
Getting raw data is the correct behaviour. You need to get the number format for that cell and apply the number format to the raw data. For instance, you can use [ssf](https://github.com/SheetJS/ssf) to format your raw data.
```
const numFmt = cell.style("numberFormat");
const formatedValue = SSF.format(cell.value(), numFmt);
```
