### ISSUE TITLE
Hyperlink support

### ISSUE THREAD

**Issue by madvedd** [dtjohnson/xlsx-populate#19]
Hi! 
Thank you for this great library!
It's better than [https://github.com/SheetJS/js-xlsx](url) because it has styles and it easier to use. And it's pretty clear inside.
Are you planning to add Hyperlink support?
I can't find similar library which can add hyperlink to cell. It will be really useful.

**Comment by dtjohnson** [comment]
Sure. I just got this working for you. I need a bit more time to get the code cleaned up and tested.

**Comment by madvedd** [comment]
it's good news! Thank you very much!

**Comment by dtjohnson** [comment]
All set. Just released v1.1.0 with hyperlink support. See the docs here:
https://github.com/dtjohnson/xlsx-populate#hyperlinks

**Comment by madvedd** [comment]
Thanks a lot! You really helped me with my work task!
