### ISSUE TITLE
How to copy sheet

### ISSUE THREAD

**Issue by keitetran** [dtjohnson/xlsx-populate#193]
Hi, 
i see 
let newSheet = wb.addSheet("Sheet " + sheetIndex);

but how to copy sheet 1 to other sheet ? 

Thank you.

**Comment by eddiecorrigall** [comment]
This feature does not exist, yet.

**Comment by zypA13510** [comment]
Closed by #199?

**Comment by Fauny** [comment]
@zypA13510 Yes, it's resolved(but has some limits): https://github.com/dtjohnson/xlsx-populate#Workbook+cloneSheet

@keitetran you can close this one.
