### ISSUE TITLE
Issue when creating a new Sheet

### ISSUE THREAD

**Issue by thaiat** [dtjohnson/xlsx-populate#2]
Using the following code
```js
var sheetNode = parser.parseFromString('<sheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" name="' + worksheetname + '" sheetId="1"/>').documentElement;
var sheetXML = parser.parseFromString('<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData><row r="1"/></sheetData></worksheet>').documentElement;
worksheet = new Sheet(workbook, sheetNode, sheetXML);
worksheet.setName(worksheetname);
console.log('creating a new worksheet', workbook.getSheet(worksheetname).getName());              
```

everything works untill last line where the new sheet does not seem to be attached to the workbook...

**Comment by dtjohnson** [comment]
It's actually a touch more complicated than that. The workbook holds the lists of sheet objects in a private array _sheets. It uses this array when it outputs the workbook. Your need sheet would need to be added into that array. The workbook XML also has a <sheets> node that needs to include the proper references to the new sheet.

Those constructors weren't really intended to be used publicly. There's unfortunately no way to mark them as private in JSDoc.

What I'll do is create a new method on the workbook called createSheet that will do what you need. I should be able to get this done tonight.

**Comment by thaiat** [comment]
nice !!!

**Comment by dtjohnson** [comment]
I just published v0.2.0, which includes a new Workbook.createSheet method. Give it a shot and see if it works for you.

**Comment by thaiat** [comment]
this is working perfectly thanks

**Comment by srjkumbhar** [comment]
Can anyone please provide with code snippet to create new sheet in existing workbook.

Thank you!
Suraj

**Comment by vitticeps** [comment]
I was having problem with the addSheet method. When I opened the generated file was prompted me an error.
I found out that the <pageMargins/> were not "filled in" in the xml.

I changed this part of the Sheet.js file -

		// Add the pageMargins if needed.
		if (this._pageMarginsNode) {
			xmlq.insertInOrder(node, this._pageMarginsNode, nodeOrder);
		}

to this -

        // Add the pageMargins if needed.
        if (this._pageMarginsNode) {
            if (this._pageMarginsNode.attributes.hasOwnProperty("left"))
                xmlq.insertInOrder(node, this._pageMarginsNode, nodeOrder);
            else
                xmlq.insertInOrder(node, {name:'pageMargins',attributes:{left:0.7,right:0.7,top:0.75,bottom:0.75,header:0.3,footer:0.3},children:[]}, nodeOrder);
        }

Now it works
Thanks
