### ISSUE TITLE
file size increases drastically

### ISSUE THREAD

**Issue by bhavyams** [dtjohnson/xlsx-populate#20]
Thanks a ton for the wonderful API. 

I am using xlsx-populate to modify few cells in an existing file (xlsm) and writing it to another xlsm file. This is a node.js application. The template file is 100kb. The new file generated with toFile() method is 700kb with only 3 fields/cells modified. I am using version 0.8.0 of the API. In addition, I have tried using the newer version (1.x) but that results in a corrupt file. Any help is deeply appreciated. Thanks!
Code looks similar to below:

xlsxPopulate.fromFile(fileName, (error, workbook) => {
if(error) { //log }
else{
workbook.getSheet(sheetname).getCell(cellname).value(newVal);
xlsxPopulate.toFile(outfile);
}

**Comment by dtjohnson** [comment]
The 0.x version didn't use compression when outputting the file, which is why the file was huge. The 1.x version uses compression correctly.

If you are getting a corrupt file with the 1.x version, there must be some regression. Could you share the workbook?

**Comment by bhavyams** [comment]
Thanks for your quick response! I am afraid I cannot share the work book due to confidentiality. Do you have any other suggestions?

**Comment by dtjohnson** [comment]
When you open the corrupt workbook in Excel does it ask you to try to recover? If so, click Yes. After recovering, it should show a window with a summary of the errors. Could you share what they window says?

Another option is the strip out any confidential information from the workbook and see if the generation still yields a corrupt workbook. If so, I could debug off of that.

**Comment by bhavyams** [comment]
The recovery window says:
Replaced Part: /xl/worksheets/sheet1.xml part with XML error.  Load error. Line 18221, column 0.

**Comment by dtjohnson** [comment]
That means there is something wrong with the generated XML in that first sheet. I'd need to see the content of that sheet1.xml before and after to figure out what is wrong. If there is nothing confidential in just that sheet I could explain how you can send me just the XML. If there is, you'll have to strip out the confidential data. I'm afraid there isn't much I can do without seeing it.

**Comment by dtjohnson** [comment]
I just updated to v1.4.0 which fixed a bug in ordering data in the sheet XML. Try updating and see if that fixed your issue.

**Comment by lizjulien** [comment]
Think this is ok, after write over 300 cells, there is no change on size here ;)

**Comment by bhavyams** [comment]
I updated to 1.4.2 and things work great. The excel file is now about 350k after updating 3 cells. Also, I found out recently that there are hidden sheets in the excel. The 1.4.2 has solved all the issues. Thanks again for a wonderful library! :)
