### ISSUE TITLE
Output file loses data and formatting

### ISSUE THREAD

**Issue by tjrhodes** [dtjohnson/xlsx-populate#21]
Hi,

I'm modifying a large file with several sheets, I modify the value of one cell and save it to file. The modified sheet contains only a couple of column headings and nothing else.

This lib is the closest I've found to matching my requirements though, it preserves the macros and other data in the file perfectly. 

What can I do to help debug it?

**Comment by dtjohnson** [comment]
Can you share the workbook? That's the easiest way to debug.

**Comment by tjrhodes** [comment]
Ok, great, is it cool to send to you privately?

**Comment by dtjohnson** [comment]
Yep. My email is on my profile.

**Comment by dtjohnson** [comment]
I just updated to v1.4.0 which fixed a bug in ordering data in the sheet XML. Try updating and see if that fixed your issue. If not, please do send me the workbook.

**Comment by lizjulien** [comment]
@tjrhodes can you say us if this is fixed ?

**Comment by tjrhodes** [comment]
Hi, I will test this afternoon, I did send the workbook to @dtjohnson too.

**Comment by tjrhodes** [comment]
@lizjulien @dtjohnson I can confirm that using 1.4.2 fixes the issue! Thank you so much. This lib may well save me from hours of monotony with excel!

**Comment by lizjulien** [comment]
;)
