### ISSUE TITLE
Column sizing feature

### ISSUE THREAD

**Issue by Climber22** [dtjohnson/xlsx-populate#211]
Is there any api to specify the size of row ?
If not, is there any plan to implement this feature?

**Comment by LesterLyu** [comment]
https://github.com/dtjohnson/xlsx-populate#Row+height

**Comment by Climber22** [comment]
Thanks.
oops, I made a mistake.
What I want to ask is "Is there any api to specify the size of colum to fit its content?"

**Comment by Climber22** [comment]
I mean, `auto fix column width`

**Comment by LesterLyu** [comment]
No, you have to do some calculations based on the font width (different by font family), which is complicated, and set the column width manually.

**Comment by Climber22** [comment]
I see.
> some calculations based on the font width
It sounds very troublesome...

Thank you for your advice, I'll try.

**Comment by Climber22** [comment]
close the issue
