### ISSUE TITLE
[Question] `Workbook.addSheet()` not changing xlsx file.

### ISSUE THREAD

**Issue by MilesZew** [dtjohnson/xlsx-populate#212]
I have a workbook with five sheets that were initially created with excel. I wanted to add a new sheet into it using `Workbook.addSheet()`. Unfortunately when I opened the file up in excel, there was no change. My question is: Is there an error with my code, if so what, or is this npm library a excel simulator, and not an editor?

Here is my code

```
const xlsx = require('xlsx-populate')

exports.totals = async function(workbookPath, input, output) {
  const workbook = await xlsx.fromFileAsync(workbookPath)
  const sheets = await workbook.sheets()
  await workbook.addSheet('My new sheet')
}

exports.totals('../WorkBook.xlsx')
```

**Comment by papb** [comment]
You have to save your modifications to the file, by calling `await workbook.toFileAsync('../WorkBook.xlsx');` in the end.

**Comment by MilesZew** [comment]
Thank you, sorry for not reading the docs more closely, closing issue now.
