### ISSUE TITLE
blank sheet

### ISSUE THREAD

**Issue by lizjulien** [dtjohnson/xlsx-populate#22]
I load a sheet with colors, formatting, formula.
I change some text in cell in a sheet and save in same path as load.
I change again some things in same sheet, other cells.
When i save this time, no problem, but when open the file, Excel say me it's broken and go repair. And my sheet is blank, all others are ok.

The first time, all is ok.

**Comment by lizjulien** [comment]
And after test, with a new sheet, there is a big problem with order of sheet, some are destructed and some are taken the previous content. Maybe the last version ?

**Comment by dtjohnson** [comment]
This is with the latest v1.4 version? Is it possible to share the workbook?

**Comment by lizjulien** [comment]
Yes, lastest. I'll send you my files by mail.

**Comment by dtjohnson** [comment]
Thanks. The issue is with the shared strings table where the various strings throughout the workbook are stored. It will take a bit to debug, but I should be able to get out fixed today.

**Comment by lizjulien** [comment]
Sounds good  :)

**Comment by dtjohnson** [comment]
OK. Just published v1.4.1, which should work now.

Thanks so much for sharing your workbook. It exposed a number of issues:

- A bug in shared string parsing that wasn't deleting the uniqueCount attribute like it was supposed to. This is fixed.
- Mishandling of significant whitespace in the XML. This is fixed.
- Inconsistency between how I was escaping XML special chars and how Excel was. This was probably not an issue but I corrected it anyway to be safe.
- A subtle race condition introduced when I eliminated bluebird. As individual sheets were parsed they were finishing at different times which caused them to be stored out of order. This is fixed.
- You have all the columns in the workbook styled. The way xlsx-populate handles this results in a very large output workbook. This is not a problem, but it is something I can fix in future releases.

**Comment by lizjulien** [comment]
Ok, i'll test it again and send you the generated, because it was again blank :)
Maybe that can help again to fix up and hope that can work :D

**Comment by dtjohnson** [comment]
The sample you just sent looks good, no? In the "Formateur" tab I see "Youpi" in F11, "super" in F12, and "erf" in F13, which I assume was added via xlsx-populate. The "Mastering" sheet is empty but it was empty in the original you sent me... What am I missing?

**Comment by lizjulien** [comment]
When opened with Excel, say broken and the tab is empty. An Excel problem  ?

**Comment by dtjohnson** [comment]
My bad. In the Gmail viewer it looked right, but Excel is complaining. Could you share your JS code?

**Comment by lizjulien** [comment]
Sent to you ;)

**Comment by dtjohnson** [comment]
Ah. I see. You are writing to file 3 times. There's something wrong with the state between subsequent writes. I'll look into it.

In the meantime, you don't need to write to file after every change. You can manipulate all together and just save to file when you are done.

**Comment by dtjohnson** [comment]
OK. I fixed it. Try v1.4.2.

**Comment by lizjulien** [comment]
YOU ROCKS 👍
