### ISSUE TITLE
How to save file as PDF ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [dtjohnson/xlsx-populate#222]
Thank you very much for your great package.
Is there any way to convert/save file as pdf with `xlsx-populate` package ? 
```javascript
XlsxPopulate.fromFileAsync("./report_sample.xlsx")
  .then(workbook => {
    workbook.sheet(0).cell("C4").value("This is neat!");
    return workbook.toFileAsync("./report_sample.pdf");
  });
```

**Comment by mbrevda** [comment]
I don't think this lib provides the rendering support that would be needed to produce a PDF. Aside from rendering, this lib also doesn't calculate formula values - making rendering to PDF pointless in many cases.
