### ISSUE TITLE
Not Issue - Need information on creation of workbook with multiple sheets

### ISSUE THREAD

**Issue by srjkumbhar** [dtjohnson/xlsx-populate#23]
how could we create a workbook with couple of sheets? Or how could we add a new sheet in existing workbook.

Thanks!
Suraj

**Comment by dtjohnson** [comment]
Ah. This is a feature I missed when moving to the 1.0 version. But I actually just rewrote it yesterday as part of a larger update. The branch is here:
https://github.com/dtjohnson/xlsx-populate/tree/activate
The code isn't fully tested yet, but you can try it if you want. I'll work on getting it tested and published.

**Comment by dtjohnson** [comment]
And here is some sample code to add a sheet:
```js
// Add sheet at end
workbook.addSheet("NAME1");

// Add sheet at beginning
workbook.addSheet("NAME2", 0);

// Add sheet before sheet named "Sheet2"
workbook.addSheet("NAME3", "Sheet2");
```

**Comment by srjkumbhar** [comment]
Thanks a ton for prompt response.

Which file contains this function?

**Comment by srjkumbhar** [comment]
Its working fine!!!

Thanks buddy!
