### ISSUE TITLE
How to read binary file ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [dtjohnson/xlsx-populate#235]
Thanks for the great package. For now, on README, I only see `xlsx-populate` can read file from `xlsx` file, but in my application, I'm storing excel file as binary (`blob`) in MySQL. Is that possible to read excel file from the blob of MySQL with xlsx-populate ?

**Comment by sickhack** [comment]
may be `fromDataAsync`

**Comment by TranBaVinhSon** [comment]
Yeah I solved it !
