### ISSUE TITLE
Draw border 1 range

### ISSUE THREAD

**Issue by tinhnqjp** [dtjohnson/xlsx-populate#236]
<img width="353" alt="Screen Shot 2019-08-16 at 17 06 24" src="https://user-images.githubusercontent.com/34364630/63153259-d2e65700-c048-11e9-9f01-8aff58cdfbac.png">
I want to draw border 1 range, I don't know how to do it

**Comment by dtjohnson** [comment]
You'll need to do it cell by cell. There is no border around feature.
