### ISSUE TITLE
UglifyJs compression error.

### ISSUE THREAD

**Issue by Aiiroo** [dtjohnson/xlsx-populate#238]
I found that the package will report an error when using UglifyJs for code compression,because es6 code in 'xlsx-populate'.
I have to manually convert them to es5 now.
Can you do a code conversion with babel for 'xlsx-populate'?

**Comment by dtjohnson** [comment]
The package does use Babel but it targets most browser so some ES6 features work their way in. If you need to transpile further you should be able to further Babel it yourself.
