### ISSUE TITLE
Resulting workbook has more columns than original

### ISSUE THREAD

**Issue by maxjanisse** [dtjohnson/xlsx-populate#24]
First, this is an amazing project.  It's been a pleasure to implement it.  Also love the amount and quality of your documentation.

I'm curious if there is a way to control the dimensions of the generated spreadsheet to prevent too many empty columns from being returned.

The project I'm working on uses a template file that I use to dynamically populate.  That file only shows columns to the width of the screen it's on, like "AC".  The file that is returned has columns all the way up to "XFC".  They are all empty so it would be nice if these could just not be returned.

Thanks!

**Comment by dtjohnson** [comment]
Is there any way you could share your workbook with me? Or a similar workbook that has the problem? It's hard to debug without it. My email is on my profile.

**Comment by maxjanisse** [comment]
Thank you so much for the quick response! Upon further investigation this morning, I was able to determine that the problem stemmed from the template file I was using (no idea how or why).  After failing to reproduce the "bug" using a fresh file, I just recreated my template and now it's better than ever.

Closing as a non-issue.
