### ISSUE TITLE
Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ?

### ISSUE THREAD

**Issue by flyskyne** [dtjohnson/xlsx-populate#245]
Hi!

First of all, thank you so much for such goooood xlsx library.

I got an error for read some xlsx files.
Here is error:
```
Uncaught (in promise) Error: Can't find end of central directory : is this a zip file ? If it is, see https://stuk.github.io/jszip/documentation/howto/read_zip.html
    at ZipEntries.readEndOfCentral (xlsx-populate.js?cc37:31441)
    at ZipEntries.load (xlsx-populate.js?cc37:31529)
    at eval (xlsx-populate.js?cc37:28875)
```

These files are created by Hancom-one of korea wordprocessor company-'s Hancell.
And no problem open it by Microsoft excel.

Please looking this file for solve a problem.
[아이엠티처_수강신청_강좌_일괄_추가 (4).xlsx](https://github.com/dtjohnson/xlsx-populate/files/3812962/_._._._.4.xlsx)

xlsx-populate Version: 1.20.0

Thanks you!!!

**Comment by flyskyne** [comment]
I notice that Hancell save a file by xls format remains it's extension to xlsx.  😱
Don't mind this ;)

**Comment by mansi-manhas** [comment]
Hi @flyskyne  , how was the issue solved here and could you share some code snippet?

**Comment by flyskyne** [comment]
Hi, @mansi-manhas .
It is a problem of 'Hancell'.
For specific case, Hancell save a file by xls format not xlsx.

If you face to error 'Can't find end of central directory', check your file's format.
xlsx-populate does not support xls format.

**Comment by varunsree** [comment]
Hi,
I got the same issue when I try to create an xlsx file to a folder. I got 2 errors in multiple attempts from node
1. `Can't find end of central directory : is this a zip file ? If it is .... `
2. `Corrupted zip or bug: unexpected signature (\x00\x00\x00\x00, expected \x50\x4B\x03\x04)`
Don't know what is the actual issue. Please help me to get rid of this. Thanks

**Comment by jwcheon** [comment]
@varunsree Hey there, did you get this solved?
