### ISSUE TITLE
How I can get a size of a cell ?

### ISSUE THREAD

**Issue by TranBaVinhSon** [dtjohnson/xlsx-populate#249]
Thanks for the great package. I need to get size of a cell, I read documentation, it seems like `xlsx-populate` supports that API. But both `width()` and `height()` functions are returning `undefined`. Are there any problems with my bellow code? 
Thanks in advance !
```js
XlsxPopulate.fromFileAsync(filePath)
  .then(workbook => {
    // this cell is exist in worksheet
    let cell = workbook.definedName("name");
    const width = cell.column().width();
    const height = cell.row().height();
    console.log("width: ", width);  // undefined
    console.log("height: ", height); // undefined
  })
  .catch(e => {
    console.log(e);
  }) 
```

**Comment by mvelluet** [comment]
Hello,

You cannot get the size of a cell, I think.

You can get the height and the width like that:
```
sheet.row(1).height();
sheet.column('A').width();
```

**Comment by dtjohnson** [comment]
XlsxPopulate can only return _custom_ widths/heights. If the cell has the default width/height it will return undefined.

**Comment by TranBaVinhSon** [comment]
@dtjohnson Is there any ways that I can get width/height of a cell by `xlsx-populate` ?

**Comment by TranBaVinhSon** [comment]
@dtjohnson So how do I know the  `default width/heigh` of a row or column ?
Hope to hear from you soon

**Comment by mvelluet** [comment]
@TranBaVinhSon my way to calculate the length of the string is one char is 1 width, and about height, one line is 15 height in excel

**Comment by TranBaVinhSon** [comment]
@mvelluet 
> my way to calculate the length of the string is one char is 1 width

I don't this a correct way. Because the width of the column could be a float (for example: 1.5)
And even we can calculate the column's width by that way, how can we convert that unit to pixel unit?
http://www.tmssoftware.biz/flexcel/doc/net/tips/understanding-excel-measurement-units.html

**Comment by mvelluet** [comment]
@TranBaVinhSon that depends following excel's version. 
1 width to excel 2017 = 15px 
before that seems to be less
