### ISSUE TITLE
How could we open the downloaded excel in IE as well as Chrome?

### ISSUE THREAD

**Issue by srjkumbhar** [dtjohnson/xlsx-populate#25]
Hello,

I am using blob to generate and download the excel file, but i want to open it as soon as its downloaded.

Its just because I want to auto close the pop up window from which user has downloaded the excel.

This will save two clicks(Open Excel & Close PopUp) per file and help to automate the process.

Thanks!
Suraj

**Comment by dtjohnson** [comment]
Nothing you can do, no. The browsers control what to do with the downloaded files. In Chrome, your users can click the little arrow icon by the download and select "Always open files of this type".

**Comment by srjkumbhar** [comment]
Ohhk!!!

Thanks for this information but i am worries, how its supported using ActiveX object!

Because the functionality i am working was written using ActiveX object which is not supported in Chrome, So i rewrote this using blob which is supported in both IE & Chrome.

Anyways, will post in case if i find some alternative.

Thanks Again!!
Suraj

**Comment by dtjohnson** [comment]
No prob. I'll close this since there isn't an issue with xlsx-populate.
