### ISSUE TITLE
How can I remove special symbols from the xlsx report

### ISSUE THREAD

**Issue by varunsree** [dtjohnson/xlsx-populate#257]
![Capture_V](https://user-images.githubusercontent.com/6636865/75340362-5dd9c100-58b8-11ea-9442-c42dd79287d2.PNG)
Hi,
I have generated a report based on the library and found some warning symbols in the excel report. It has shown only in the windows machine. How can I remove the warning symbols from the report?
Thanks

**Comment by dtjohnson** [comment]
Those look like "number formatted as text" errors. You can specify a number format and it'll go away.

**Comment by varunsree** [comment]
I agree but that field should be numeric or text. See 1002 as numeric but 3300-W how it's treated like. Thanks
