### ISSUE TITLE
Automatically set column-width to "fit" data

### ISSUE THREAD

**Issue by maxjanisse** [dtjohnson/xlsx-populate#26]
Is this already a feature in the project, or is there a pattern you would suggest, that would make it so the columns of the generated spreadsheet "fit" their largest piece of data?  This same behavior can be achieved in Excel by double-clicking on the right-hand edge of a column-header (after it turns into the resize cursor).

I'm positive that I will be able to get this result using the methods you've already provided in the API, but I figured I'd ask if you had any suggestions first before I start getting into it.

Thanks!

**Comment by dtjohnson** [comment]
That's a tricky one. Excel renders the text (including formatting, font size/family, word wrapping, etc.), finds the largest rendered width, and then just sets the column width to that size. Since xlsx-populate doesn't do rendering that's not possible.

Given the wide range of rendering options there isn't a general solution to the problem, but here is a pattern that should work. You basically need to iterate through all the cells in the column, count the number of characters in each cell, find the max length cell and then set the width based on that. Something like this:
```js
const maxStringLength = sheet.range("A1:A20").reduce((max, cell) => {
    const value = cell.value();
    if (value === undefined) return max;
    return Math.max(max, value.toString().length);
}, 0);

// For the default font settings in Excel, 1 char -> 1 pt is a pretty good estimate.
sheet.column("A").width(maxStringLength);
```

**Comment by maxjanisse** [comment]
Awesome!  Thank you so much for the explanation, advice and code example.  Since I can control the font settings, I can always do tweaking to that "1 char -> 1 pt" relationship, if need be.

**Comment by ndrwa** [comment]
@dtjohnson Hi. Are there any workarounds how to set row height to fit data?
I changed your example a little bit

```javascript
const maxStringLength = sheet.range("A1:E1").reduce((max, cell) => {
    const value = cell.value();
    if (value === undefined) return max;
    return Math.max(max, value.toString().length);
}, 0);

// For the default font settings in Excel, 1 char -> 1 pt is a pretty good estimate.
sheet.row(1).height(maxStringLength);
```
But it doesn't work the way I expected. The space between text and cell borders are so big.
Thank you.

**Comment by papb** [comment]
Hi @andreidolhaniuk, I created a module [@papb/json-excel](https://github.com/papb/json-excel) that converts JSON data to `.xlsx`, automatically fits cell rows and column sizes to content. Maybe it helps you!

**Comment by sagarpomal** [comment]
@andreidolhaniuk Hi, were you able to find any workaround for height?

**Comment by sentientmachin3** [comment]
> Hi @andreidolhaniuk, I created a module [@papb/json-excel](https://github.com/papb/json-excel) that converts JSON data to `.xlsx`, automatically fits cell rows and column sizes to content. Maybe it helps you!

Actually super f***ing sick, thanks!

**Comment by papb** [comment]
@sentientmachin3 Glad you liked 😄
