### ISSUE TITLE
corrupted file issue

### ISSUE THREAD

**Issue by vasdhara** [dtjohnson/xlsx-populate#281]
xlsx-populate generates a workbook that opens well in LibreOffice, google sheets, etc, but when I try to open it in Microsoft office, I get a file that is corrupted error. Are there any specific steps to be taken to prevent this? I can attach data/code whatever may be required to help

**Comment by papb** [comment]
@vasdhara Can you show a screenshot of the error?

**Comment by vasdhara** [comment]
![image](https://user-images.githubusercontent.com/34437245/85282891-1bad3e80-b4aa-11ea-9119-4250b22e15f3.png)
![image](https://user-images.githubusercontent.com/34437245/85282923-27006a00-b4aa-11ea-83dc-e5f259e3063d.png)

**Comment by papb** [comment]
:thinking: Can you provide a minimal code example that generates such file?

**Comment by vasdhara** [comment]
```js
const createWorkbook = async (tabs) => {
  let workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(__dirname + "/fantemplate.xlsx");
  console.log(`Number of tabs: ${Object.keys(tabs).length}`);
  sourceWorksheet = workbook.getWorksheet(1);
  let finalWorkbook = new ExcelJS.Workbook();
  Object.values(tabs).forEach((tab) => {
    let targetSheet = finalWorkbook.addWorksheet();
    targetSheet.model = Object.assign(sourceWorksheet.model, {
      mergeCells: sourceWorksheet.model.merges,
    });
    targetSheet.name = tab.system;
    let cell = targetSheet.getCell("C3");
    cell.value = tab.system;
  });

  return finalWorkbook;
};

 ```

**Comment by papb** [comment]
Looks like you're using `exceljs`, and not `xlsx-populate`

**Comment by vasdhara** [comment]
damn sorry, I messed up reading the imports and opened it in the wrong repo. much apologies. thank you for the support
