### ISSUE TITLE
Sheet dimension range not being updated

### ISSUE THREAD

**Issue by maxjanisse** [dtjohnson/xlsx-populate#29]
It looks like the `dimension` node in `~/xl/worksheets/sheet1.xml` is not being updated to reflect when data is added to the sheet dynamically.  

You can see that in the file `example-with-image-and-named-cell.xlsx` the cell `B11` has my old target value of "${data}".  Looking at the `dimension` node for that file, you'll simply see `B11` being referenced.  The data is then dynamically added to the sheet starting at that cell and expanding out as necessary.  In the `out.xlsx` file, you can see that all the data is there, but inspecting the `dimension` node it still shows `B11`.

Let me know if you need any more information.  Thanks!

[example-with-image-and-named-cell.xlsx](https://github.com/dtjohnson/xlsx-populate/files/873332/example-with-image-and-named-cell.xlsx)
[out.xlsx](https://github.com/dtjohnson/xlsx-populate/files/873333/out.xlsx)

**Comment by dtjohnson** [comment]
I see it. It looks like that node is [optional](https://msdn.microsoft.com/en-us/library/documentformat.openxml.spreadsheet.sheetdimension(v=office.14).aspx). Rather than try to properly update it, I'd rather just delete it from the output altogether.

Is there some reason you needed it updated?

**Comment by maxjanisse** [comment]
Nope! Looks like it not being there solves my problem.

Reason I found this was because a colleague attempted to use our processing code on one of his exported spreadsheets and found it wasn't returning everything. Turns out it was because it was paying attention to this node since it was defined.

**Comment by dtjohnson** [comment]
Got it. So it sounds like I should publish an update that kills that node?

**Comment by maxjanisse** [comment]
Please do!  That would be awesome.  Thank you.

**Comment by maxjanisse** [comment]
Beautimus!  Looks good to me.  Thanks again.
