### ISSUE TITLE
adding new line in cells?

### ISSUE THREAD

**Issue by dadamssg** [dtjohnson/xlsx-populate#301]
i'm trying to add a new line to a cell and i can't get it to work. Not sure if it's a bug or i'm doing something wrong. 

pseudo code: 
```js
const rt = new RichText()
rt.add('hello\nworld')
sheet.cell('A1').value(rt).style({wrapText: true})
```

It sets the wrap text property on the cell but my `\n` is ignored. I would expect there to be a line break in the cell.

**Comment by papb** [comment]
Did you figure it out?

**Comment by dadamssg** [comment]
@papb hi yes, it was my own fault. i did not realize i had code that explicitly removed certain tokens which was causing the issue:
```js
value.replace(/[^\x20-\x7E]/g, '')
```

While i have you...is there a setting to expand cells to fit their data? like the opposite of `shrinkToFit`?

**Comment by papb** [comment]
> While i have you...is there a setting to expand cells to fit their data? like the opposite of `shrinkToFit`?

@dadamssg Like this?

![](https://raw.githubusercontent.com/papb/json-excel/master/readme-example.png)

I ended up developing my own library (on top of exceljs) to achieve exactly this: https://github.com/papb/json-excel/
