### ISSUE TITLE
"find" unable to search for numbers

### ISSUE THREAD

**Issue by ryansalatti** [dtjohnson/xlsx-populate#325]
### Issue: 
The find function is unable to search for numbers within an excel sheet.

`const numberTest = async() => {     
     var logicSheetURL = "./test/numbertest.xlsx";     
     await XlsxPopulate.fromFileAsync(logicSheetURL)
         .then(workbook => {      
           const sheets = workbook.sheets();      
          sheets.forEach((r,index) => {       
            var f = r.find("2");         
           console.log(f);     
        });        
   });         
}`

### Attempted workarounds I've tried: 
- Changing the cell's datatype within Excel
- Using an equation (=2)

This might be a feature request(?). Any insight would be appreciated!

Thank you.

**Comment by ryansalatti** [comment]
In Cell.js:

Changed
`if (typeof value !== 'string') return false;`

To
`if (typeof value !== 'string' && typeof value !== 'number') return false;`

See: Added finding numbers: #326

**Comment by papb** [comment]
Why did you close the issue?

**Comment by ryansalatti** [comment]
> Why did you close the issue?

I'm not sure to the extent of how xlsx-populate determines the type of cell values. It seemed no matter what workaround within the actual excel sheet that I used, it always failed to get the value (because its a number and not a string). I was able to fix this by changing the limitations on value type. You can see the change here: #326  . I've been running with this change for about 2 weeks now, everything seems to be working fine.
