### ISSUE TITLE
Surviving Minified and Uglified

### ISSUE THREAD

**Issue by simonaberry** [dtjohnson/xlsx-populate#33]
Has anyone had any luck getting the (browser) library to be minified and uglified....

My build process  (based on grunt) seems to be breaking something, somewhere... 

first error : "n is not defined" at the first line (remembering that n is probably a minified name)
```
var g = n("../utils")
                  , h = n("./ConvertWorker")
                  , i = n("./GenericWorker")
                  , j = n("../base64")
                  , k = n("../support")
                  , l = n("../external")

```
which leads to an  "Uncaught ReferenceError: XlsxPopulate is not defined" in my code

**Comment by dtjohnson** [comment]
Hmmmm... I was able to uglify/minify fine with [uglify-js](https://www.npmjs.com/package/uglify-js) even with mange and compress.

Which uglifier are you using? And what options? Could you give a full example?

**Comment by dtjohnson** [comment]
I'm going to close this as there was no response. Feel free to reopen if you have more detail.
