### ISSUE TITLE
Wrong parsing - getting for each sheet the data of the one sheet after it

### ISSUE THREAD

**Issue by eschneor** [dtjohnson/xlsx-populate#348]
I parse a lot of files with this excellent library and all works well. Now, I have one file that I get wrong data from parsing, seems I get for each sheet the data of the one sheet after it.
E.g. for `sheet1.cell('A1').value()` I get the data that exists in `sheet2` cell `A1`.
Maybe something wrong with my file but I can't point it. Any idea?

Thanks!

**Comment by mp3por** [comment]
Please share your file. There is no way to help you just from the information you have provided.
