### ISSUE TITLE
An option for numberToDate to indicate what should the date be accurate to

### ISSUE THREAD

**Issue by buffaybu** [dtjohnson/xlsx-populate#35]
Hi.
[095959.xlsx](https://github.com/dtjohnson/xlsx-populate/files/915909/095959.xlsx)
As the file shows in Excel, B2 is `10:00:00`, but it is actually `09:59:59.995` and Excel rounds the value to `10:00:00` because B2's number format doesn't include milliseconds.

Converted by `numberToDate`, the date instance's getters of hours/minutes/seconds return 09/59/59, which is different from what users see in Excel.

So it might be useful to have an option for `numberToDate` to indicate that what should the date be accurate to.

**Comment by dtjohnson** [comment]
Not sure I understand this one. The date being returned for B2 appears to be correct according to the value in the cell. The fact that Excel rounds it is just a matter of formatting, which is clear from C2, where you have added milliseconds to the formatting.

If you want to round the date to the nearest second you could use something like this:
```js
date.setSeconds(date.getSeconds() + Math.round(date.getMilliseconds() / 1000));
date.setMilliseconds(0);
```

Alternatively, you could use [Moment.js startOf](http://momentjs.com/docs/#/manipulating/start-of/).
