### ISSUE TITLE
Writing to cells becomes corrupt

### ISSUE THREAD

**Issue by shanewoodruff** [dtjohnson/xlsx-populate#40]
When I run the following code and open the file, it appears that column B is becoming corrupt and lost. Using a new workbook or an existing one has the same problem.

`for (var idxRow = 0; idxRow < 30; idxRow++) 
     {
          for (var idxColumn = 0; idxColumn < 30++) {
                workbook.sheet(0).cell(7 + idxRow, idxColumn).value("Row: " + idxRow.toString() + " Column: " + idxColumn.toString());
          }
}`

**Comment by dtjohnson** [comment]
Could you please provide a complete working script that exhibits the issue?

**Comment by shanewoodruff** [comment]
Please see [http://jsbin.com/mutehiqaho/edit?html,output](url)

**Comment by dtjohnson** [comment]
The issue is that you are using 0 for the column number. The numbers are 1-based to match Excel's behavior. xlsx-populate _should_ throw an error if you use a number <= 0 but it doesn't. I'll fix that.

**Comment by shanewoodruff** [comment]
Thank you for the quick response. I had misunderstood the documentation here: [https://github.com/dtjohnson/xlsx-populate#Range+cell](url)
