### ISSUE TITLE
When I try to ad a value to a Cell it prints undefined

### ISSUE THREAD

**Issue by area73** [dtjohnson/xlsx-populate#41]
Hi,
I'm trying to add some dynamic values to new cells like this
this._worksheet.cell("H7").value(dynVal);

I double check dynVal and I have a value but when I try to see the value inserted I got a 'undefined'
I made sure that dynVal was a string.

Any ideas?

Thanks

**Comment by area73** [comment]
For some reason if I add a string to the var it will work :

let newDynVal = dynVal + ' ';
this._worksheet.cell("H7").value(newDynVal);

**Comment by dtjohnson** [comment]
That's odd. Could you include a full code example that exhibits the issue?
