### ISSUE TITLE
Replacing the fsevents dependency?

### ISSUE THREAD

**Issue by ManuelTS** [dtjohnson/xlsx-populate#42]
I installed it with
`npm install --save xlsx-populate`
on my ubuntu 17.04 with the npm version 3.5.2.
```
ERROR in ./~/xlsx-populate/lib/Workbook.js
Module not found: Error: Can't resolve 'fs' in '/home/oct/Documents/Workplace/web-app/node_modules/xlsx-populate/lib'
 @ ./~/xlsx-populate/lib/Workbook.js 4:11-24
 @ ./~/xlsx-populate/lib/XlsxPopulate.js
 @ ./src/components/TemplateForm/index.js
 @ ./src/containers/Template/index.js
 @ ./src/containers/index.js
 @ ./src/routes.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:3000 webpack/hot/dev-server ./src/main
```
the reason is the dependency fsevents, since when I try to install it with
`npm install --save fsevents`
i get
```
npm ERR! Linux 4.10.0-20-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "fsevents"
npm ERR! node v4.7.2
npm ERR! npm  v3.5.2
npm ERR! code EBADPLATFORM

npm ERR! notsup Not compatible with your operating system or architecture: fsevents@1.1.1
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/oct/Documents/Workplace/web-app/npm-debug.log
```
Maybe you want to consider replacing the fsevents dependency with another one which works on all systems?

**Comment by dtjohnson** [comment]
We don't use fsevents. We do use the standard Node fs though. Your error looks related to webpack. Seems like a common occurrence: http://stackoverflow.com/questions/39249237/node-cannot-find-module-fs-when-using-webpack

**Comment by ManuelTS** [comment]
Thanks! You pointed mi into the right direction, after further searching on the web adding 
```node:{fs: 'empty'}``` 
to my `base.js` from webpack resolved the error.
