### ISSUE TITLE
row().value() not available

### ISSUE THREAD

**Issue by Aymkdn** [dtjohnson/xlsx-populate#43]
Hi,

It looks like that adding a value for a Row is not possible.

We can set a value for a cell;
```javascript
sheet.cell("A1").value("something")
```
Or for a range:
```javascript
sheet.range("A1:B1").value([ ["val1","val2"] ])
```

But not for a row:
```javascript
sheet.row(1).value(["val1","val2"]) // →  TypeError: sheet.row(...).value is not a function
``` 
I think it would make sense to have `value()` for ` Row` too, especially because it's easier to manipulate a row than a range while writing into a file.
For example:
```javascript
let row=1;
dataArray.forEach(data => {
  sheet.row(row++).value([data.valA, data.valB]);
})
```

Thanks

**Comment by dtjohnson** [comment]
That's an interesting idea. We could also add that for Column and Sheet as well. So to extract the values from the sheet you could just do:
```js
const values = sheet.value();
```

Would you imagine just getting/setting arrays of values? [Range.value](https://github.com/dtjohnson/xlsx-populate#Range+value) supports setting by an array of values, a single value for all cells, or a callback function. I suppose the latter two wouldn't work for an unbound selection...

**Comment by manikmi** [comment]
Hi @dtjohnson,

I tried this line of code with my simple flat excel file a single sheet "Sheet1" with data:

`const values = workbook.sheet("Sheet1").value();`

but it failed with the error:
TypeError: workbook.sheet(...).value is not a function

I am able to get data for single using this line:
`const value = workbook.sheet("Sheet1").cell("A1").value();`

What is the correct to access all of the sheet data?
I am using xlsx-populate@1.17.0 with my nodejs api on backend.

Regards,
Manik Mittal

**Comment by manikmi** [comment]
Actually, I was able to get the data from the worksheet, using the following code:
```
const sheet = workbook.sheet(0);
const usedRange = sheet.usedRange();
const values=usedRange.value();
```

**Comment by dtjohnson** [comment]
Closing since `usedRange` does the job.
