### ISSUE TITLE
Cannot instead any value to excel file

### ISSUE THREAD

**Issue by adarshlilha** [dtjohnson/xlsx-populate#46]
const XlsxPopulate = require('xlsx-populate');
XlsxPopulate.fromFileAsync("myfile.xlsx")
    .then(workbook => {
        const r = workbook.sheet(0).range("D2:D50");
        r.value(55);
        var q = 4;
        sheet(0).cell("D4").value(q.toString());
});

None of these two works while trying to insert value(s) into excel

**Comment by dtjohnson** [comment]
Did you write the workbook back to file after editing it?
