### ISSUE TITLE
How do I get 01 as a string

### ISSUE THREAD

**Issue by area73** [dtjohnson/xlsx-populate#51]
I'm trying to get a value from a cell that is "01" but when I use ... row("A7").value() it will return a number 1 and I want to retrieve "01" as a string 
Any idea ?

Thanks

**Comment by dtjohnson** [comment]
Sounds like the value in your cell is stored as the number 1 but has some formatting like "00" that presents it in Excel as "01". You can see this if you select the cell in Excel and look at the value in the formula bar. The xlsx file only stores the underlying value, not the formatted one. So that is all xlsx-populate can return to you.

You could try reformatting the value yourself using some library like [this](https://github.com/SheetJS/ssf). You can get the current cell number format using `cell.style("numberFormat")`.

**Comment by hebaek** [comment]
I want someone to reopen this issue.

I have the same problem, but my cells are not formatted as numbers at all, but as text. The cell.style('numberFormat') is simply '@'.
My data is a mix of 'normal' strings and strings consisting of only numbers - some of which are starting with '0' - and I need to get them as strings.
Can anyone help with this?

Thank you!

**Comment by area73** [comment]
what I did was to add a non numeric character like a ' in the begining of the cell which is realy an hugly work around

**Comment by hebaek** [comment]
Yeah, and I can't do that, unfortunately. I guess there is some property which lets Excel store there strings as pure text, and that the library currently doesn't support that. I have no clue how to solve this, but the first answer you got must be based on a misunderstanding, so I hope this issue can be reopened and looked at properly.

**Comment by dtjohnson** [comment]
@hebaek, could you share an example workbook I can take a look at?

**Comment by dtjohnson** [comment]
Actually, I think I might know the issue. Strings and numbers both get serialized into XML nodes the same way by Excel. When we parse the XML we convert anything that looks like a number into one. Unfortunately, `Number("01") === 1`. I'll have to rethink that a bit...

**Comment by hebaek** [comment]
Here are three very simple documents.
I wrote '01' in cell A1 in all documents, but the cells are formatted differently.
'Number - simple.xlsx': Standard formatting and content type.
'Number - formatted.xlsx': Formatted the number as '00' - the cell shows '01'.
'Number - text.xlsx': Set the cell content type to text - the cell shows '01'.

I hope this helps!

[Number - formatted.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1082441/Number.-.formatted.xlsx)
[Number - simple.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1082442/Number.-.simple.xlsx)
[Number - text.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1082443/Number.-.text.xlsx)

**Comment by dtjohnson** [comment]
OK. I just published v1.8.0 that should resolve the issue. Please give it a try and let me know.

**Comment by hebaek** [comment]
This solved the issue for me. Thank you so much for taking time to fix these issues - it makes me warm and fuzzy inside...
