### ISSUE TITLE
Returning wrong font color

### ISSUE THREAD

**Issue by duvemula** [dtjohnson/xlsx-populate#52]
Hi dtjohnson ,
Thank you very much for your xlsx-populate module. I am able to get cell values from excel sheet but when I retrieving the font color of cell it returning wrong color. for example I retrieving font color from a cell it has red color but it returning yellow. Could you please  take a look ?. 
Please let me know if you want more information.
Regards,
Durga Prasad

**Comment by dtjohnson** [comment]
That's interesting. Xlsx-populate simply returns the value stored in the workbook without manipulation. Could you share an example workbook and sample code that exhibits the issue?

**Comment by duvemula** [comment]
Code snippet: 
 XlsxPopulate.fromFileAsync('' + filePath + '/Example With Heat Map - Example With Heat Map (6).xlsx')
      .then(workbook => {
          var fontColor = workbook.sheet('Sheet2').cell('B14').style('fontColor');
          console.log(fontColor);
        });

[Example With Heat Map - Example With Heat Map (6).xlsx](https://github.com/dtjohnson/xlsx-populate/files/1061822/Example.With.Heat.Map.-.Example.With.Heat.Map.6.xlsx)

**Comment by dtjohnson** [comment]
It looks OK to me. The output I get is `{ rgb: 'FFFC0B0B' }`. That is an ARGB value. The first FF is the alpha channel. The rest is a [shade of red](http://www.colorhexa.com/fc0b0b).

**Comment by duvemula** [comment]
Thank you very much @dtjohnson . Sorry I didn't remove alpha channel. it's working fine.
Do you have a module to extract data from pdf ?

**Comment by duvemula** [comment]
I want to get background color of cell. Can I user style('fill') or anything other method is there?

**Comment by dtjohnson** [comment]
Not me, no. I do know there are some packages on npm for that.
