### ISSUE TITLE
Have problem with recored 10000+?

### ISSUE THREAD

**Issue by thearabbit** [dtjohnson/xlsx-populate#55]
I try to generate for exist file template, and insert records 10000+.
I have problem with download (don't complete).
And then I open file download

![image](https://user-images.githubusercontent.com/4495160/27208212-96f7f964-526e-11e7-8cf0-924f9615ca8d.png)

My code
```js
// Meteor method server
Meteor.methods({
    async postExcelReport(){
        if (Meteor.isServer) {
            // Template file
            let templateFile = Meteor.absolutePath + '/private/template.xlsx';

            // Load an existing workbook
            let wb = await XlsxPopulate.fromFileAsync(templateFile);
            let sheet = wb.sheet("Sheet1");

            // Data
            let data = Posts.find({});
            let startRow = 6;
            let row = 0;
            for (let index = 0; index < 10000; index++) {
                row = startRow + index;

                sheet.cell(`A${row}`).value(index);
                sheet.cell(`B${row}`).value('title');
                sheet.cell(`C${row}`).value('body');
                sheet.cell(`D${row}`).value('type');
                sheet.cell(`E${row}`).value('true');
                sheet.cell(`F${row}`).value('date');
                sheet.cell(`G${row}`).value(100);
            }

            // Footer
            let lastRow = row + 1;
            sheet.range(`A${lastRow}:F${lastRow}`)
                .merged(true).value('Total: ')
                .style({bold: true, horizontalAlignment: 'right'});
            sheet.cell(`G${lastRow}`).formula(`=SUM(G${startRow}:G${row})`);

            // Style
            sheet.range(`Annb${startRow}:G${lastRow}`).style({border: true});

            // Write to file.
            return wb.outputAsync("base64");
        }
    },
});
-----------------
// Client
                Meteor.call('postExcelReport', {type: 'Education'}, function (err, res) {
                    location.href = "data:" + XlsxPopulate.MIME_TYPE + ";base64," + res;
                });

```
In browse console
![image](https://user-images.githubusercontent.com/4495160/27208574-a50ede76-5270-11e7-8ba4-8490c6b2e9aa.png)

**Comment by dtjohnson** [comment]
Looks like you are serializing the workbook into a data URI string. The data URI string has length limitations: https://stackoverflow.com/questions/695151/data-protocol-url-size-limitations

**Comment by thearabbit** [comment]
Could you solve me for this?

**Comment by thearabbit** [comment]
I tried to create file on server only.
```js
             wb.toFileAsync(Meteor.absolutePath + '/private/out.xlsx');
            return 'success';
```
And then I go to the server folder, open the `out.xlsx`.
It still has problem

![image](https://user-images.githubusercontent.com/4495160/27248849-70f359aa-5333-11e7-802b-71bc4e256b93.png)

**Comment by dtjohnson** [comment]
The problem is where you are setting the border styles. The current implementation will create a style for every cell in the range, which will create more styles than the workbook is able to hold. You can try to style the entire columns or style the template instead.

**Comment by thearabbit** [comment]
Thanks for your reply.
But don't understand `...try to style the entire columns or style the template instead`.
Please...

**Comment by dtjohnson** [comment]
See the docs for Styles: https://github.com/dtjohnson/xlsx-populate#styles

**Comment by thearabbit** [comment]
I do this already
```js
// Style
sheet.range(`Annb${startRow}:G${lastRow}`).style({border: true});
```
could example?

**Comment by dtjohnson** [comment]
Read the part about row and column styles.

**Comment by thearabbit** [comment]
Thanks again, I will try soon

**Comment by thearabbit** [comment]
I tried insert border style by row
```js
for (let index = 0; index < 10000; index++) {
                row = startRow + index;

                sheet.cell(`A${row}`).value(index);
                sheet.cell(`B${row}`).value('title');
                sheet.cell(`C${row}`).value('body');
                sheet.cell(`D${row}`).value('type');
                sheet.cell(`E${row}`).value('true');
                sheet.cell(`F${row}`).value('date');
                sheet.cell(`G${row}`).value(100);

               // Style
               sheet.range(`A${row}:G${row}`).style({border: true});
            }
```
but still problem.
could you solve?

**Comment by dtjohnson** [comment]
You're still not styling rows or columns. I mean doing something like `sheet.row(1).style({ border: true })` or `sheet.column('A').style({ border: true })`.

**Comment by thearabbit** [comment]
Oh, It mean that it set border to all column in row 1 `sheet.row(1).style({ border: true })`.
but my column `A -> G`???

**Comment by dtjohnson** [comment]
Then do it for all of them.

**Comment by thearabbit** [comment]
I am still having problem, `sheet.row(1)` to set the border to all column of row 1.
But my column is `A -> G`???
