### ISSUE TITLE
Find method match results alternately

### ISSUE THREAD

**Issue by cimasim89** [dtjohnson/xlsx-populate#57]
In a worksheet, inserting the same text into several cells by using the "find" method of the worksheet, only a few cells are identified, it seems that the problem is due to the "/ g" the regex object will save state between calls.
Possible workaround in use _.clone(pattern) into regexify.js instead of using the old object, but I don't know if it is the best solution,

**Comment by dtjohnson** [comment]
Good catch! This should be fixed now in v1.8.1.
