### ISSUE TITLE
DataValidation/lists for a cell?

### ISSUE THREAD

**Issue by alandoyle95** [dtjohnson/xlsx-populate#61]
just wondering if this is a planned feature? I'm working on some software what I will need do be able to make dropdowns at some point.

love your work so far, its the best out there for read/writing excel and not breaking stuff.
would love to donate to this project for this feature

**Comment by dtjohnson** [comment]
It would be great to add it. I don't haven the bandwidth to do it myself at the moment, but it looks like pretty straightforward XML in the sheet*.xml files:
```xml
<dataValidations count="1">
    <dataValidation type="list" allowBlank="1" showInputMessage="1" showErrorMessage="1" sqref="D4">
        <formula1>"foo,bar,baz"</formula1>
    </dataValidation>
</dataValidations>
```

We could probably get away with Cell.dataValidation and Range.dataValidation getter/setters that give/take a JSON object.

**Comment by alandoyle95** [comment]
awesome, this will be an extremely helpful advancement :D

**Comment by dtjohnson** [comment]
That's a neat idea, but that particular syntax wouldn't work. `Workbook.definedName` could return a `Range`, which has a `value` overload that takes an array of values. I would expect this feature would look something like this:
```js
cell.dataValidation({
    type: "list",
    allowBlank: true,
    showInputMessage: true,
    showErrorMessage: true,
    formula: "foo,bar,baz"
});
```

We could have an overload that takes an array like:
```js
cell.dataValidation(["foo", "bar", "baz"]);
```

**Comment by alandoyle95** [comment]
yea I saw that as I dove into the code today, was going to try to figure out how your code all worked so I could see about adding it in myself and then testing it, but that is not as easy to learn as I was hopping :D haha so it might take me a while

**Comment by alandoyle95** [comment]
don't suppose you would add this if you had a windows VM to remote too to use my bandwidth instead of yours? XD haha I can't figure out how to add this, my brain is not wired to realize how the XML gets put into objects
