### ISSUE TITLE
XLSX-Populate:Unable to read the formulated cell values from the xlsx file

### ISSUE THREAD

**Issue by nagarjunakrishna** [dtjohnson/xlsx-populate#66]
Hi Team, Below is the programme where i am trying to write and read the data from same excel file(Ex:Test1.xlsx).I am able to write the data into excel file but when i am trying to read the formulated cell values then the null/blank values are getting returned by the programme.Could you please help me to find out the solution for the issue

var Workbook = require('xlsx-populate');
var workbook = Workbook.fromFileSync("./Test1.xlsx");
workbook.getSheet("Sheet1").getCell("B1").setValue("FRIEND");
workbook.toFileSync("./Test1.xlsx");

if (typeof require !== 'undefined') XLSX = require('xlsx');
var workbook = XLSX.readFile('./Test1.xlsx');
var first_sheet_name = workbook.SheetNames[0];
var worksheet = workbook.Sheets[first_sheet_name];
var desired_cell = worksheet["C1"];
var desired_value = desired_cell.v;
console.log("C1 Cell value:" + desired_value);

Test1.xlsx:
1.Initially, The excel contains below values.
A1 Cell:'HELLO'
B1 Cell:'WORLD'
C1 Cell:concatenate(A1,B1)==>HELLOWORLD
2.Output of the programme.
Actual result:
C1 Cell value:Returned some Blank value.
Expected result:
C1 Cell value:HELLOFRIEND

nodes installed:
npm install xlsx-populate@0.4.0
npm install xlsx

kindly help me to resolve the issue.Appreciate your support in advance.Thanks

**Comment by nagarjunakrishna** [comment]
Attachment:[Test1.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1146004/Test1.xlsx)

**Comment by alandoyle95** [comment]
your code was not working due to how it was programmed... the code below should work just fine

```
var Workbook = require('xlsx-populate');
//load the file THEN
Workbook.fromFileSync("./Test1.xlsx").then(workbook =>
{
    //Set the value
   workbook.getSheet("Sheet1").getCell("B1").setValue("FRIEND");

    //finally save the changes to the file
   return workbook.toFileSync("./Test1.xlsx");
})
```
