### ISSUE TITLE
Cell with percentage format lost value on save

### ISSUE THREAD

**Issue by sergeyKhristenko** [dtjohnson/xlsx-populate#67]
Steps to reproduce:
1. Create a .xlsx
2. Select a cell and set percentage format type
3. Set value as 0.015 (15%)
4. Open and save the file using xlsx-populate
5. Open saved file and check the value

![selection_674](https://user-images.githubusercontent.com/18219232/28321495-11442ec8-6bdc-11e7-8c65-60c81808c7b2.png)

js snippet to reproduce:
`const
  fs = require('fs'),
  Workbook = require('xlsx-populate'),
  yourFileName;

let populate = Workbook.fromFileAsync(yourFileName)
  .then(workbook => {
    populateSheet = workbook.sheet(0);
    return workbook.toFileAsync("./newFile.xlsx");   
  })`

**Comment by alandoyle95** [comment]
can't reproduce with LibreOffice on Ubuntu on a fresh XLSX file.

Are you doing a Custom percentage format ? or the built in one?

could you provide the file you used so I can test that particular file and see if I can reproduce?

**Comment by sergeyKhristenko** [comment]
Yes, I'm sorry. Totally forgot to mention anything about the system. The file was created in Microsoft Excel 2013 (15.0.4569.1504). Once it was created in MS Excel the issue is reproducing in both Ubuntu LibreOffice and MS Excel. Please have a look at zip archive in the attachment.
Built in format 
![selection_676](https://user-images.githubusercontent.com/18219232/28355500-efd7ce52-6c6c-11e7-85d6-81ded25cce41.png)
[formatIssue.zip](https://github.com/dtjohnson/xlsx-populate/files/1158359/formatIssue.zip)

**Comment by alandoyle95** [comment]
I'll check this at work today, and just checking.. are you on the latest version of xlsx-populate? And also are you doing it with browser side or node side?

**Comment by sergeyKhristenko** [comment]
I'm using xlsx-populate@1.8.2;
node side;

**Comment by alandoyle95** [comment]
Ok, I'll run this with excel 15 and check... but based on your files there is a lot more than just styles that are lost, there is a very large file size difference

**Comment by alandoyle95** [comment]
ok, using the supplied file `before.xlsx`  I can reproduce this.
I'll do more testing.

(reproduced with LibreOffice Ubuntu, Node v6.11.0)

**Comment by alandoyle95** [comment]
OK, confirmed that for windows Excel 15 AND 16 this is a bug.

here are the test files from below.

[test-files.zip](https://github.com/dtjohnson/xlsx-populate/files/1159929/test-files.zip)

**Comment by dtjohnson** [comment]
Turns out the problem was that for some reason in your before workbook Excel was storing the number in scientific notation, which wasn't being parsed as a number correctly. I fixed this and published v1.9.0.
