### ISSUE TITLE
Hide grid Line function?

### ISSUE THREAD

**Issue by henrych4** [dtjohnson/xlsx-populate#70]
Is there a hide grid line function available in this library? Thanks!

**Comment by alandoyle95** [comment]
I don't think so, but I'll look. and maybe even add it in..

**Comment by alandoyle95** [comment]
it looks like there is for rows..

Set:
```
hidden(true)
hidden(false)
```

Get:
`hidden()`

**Comment by henrych4** [comment]
Thanks!

**Comment by alandoyle95** [comment]
You're Welcome :)

**Comment by dtjohnson** [comment]
I just added [Sheet.gridLinesVisible](https://github.com/dtjohnson/xlsx-populate#Sheet+gridLinesVisible), which should do what you want. Published in v1.10.0.

**Comment by alandoyle95** [comment]
Oh. Grid lines.. not hide columns... duhh

**Comment by alisonsantosofc** [comment]
Thank you my friends this helped me a lot.
