### ISSUE TITLE
workbook.outputAsync() generates invalid files

### ISSUE THREAD

**Issue by mrburrito** [dtjohnson/xlsx-populate#73]
I'm trying to use `workbook.outputAsync()` on a Node server (6.10.2), returning it to the requester as an attachment through Express. I'm getting an error saying the file is corrupt and cannot be opened by both Excel and Libre Office. If I use `workbook.toFileAsync()` on the Node server, it opens properly, but I'd prefer to avoid writing that temp file since I have everything I need in memory!

Not sure if I'm doing something wrong or if there's a bug in `outputAsync()`. Here's a simplified version of my code:

```typescript
this.router.post('/export', (req, res) => {
  exportResults().then(data => {
    const filename = 'my-export.xlsx';
    res.set('Content-Type', MIME_TYPES.EXCEL);
    res.attachment(filename);
    res.send(data);
  });
});

function exportResults(): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    xlsxPopulate.fromBlankAsync().then(workbook => {
      // generate single sheet and populate with data
      workbook.outputAsync().then(data => resolve(data));
    });
  });
}
```

**Comment by mrburrito** [comment]
Figured it out. The problem was with the way the Swagger doc page was providing the file. When I hit the URL directly, the file opens properly.

**Comment by Serj-M** [comment]
If you download this excel file from the server side (In my case Node JS). 
The problem is solved by one line on the client side:  **req.responseType = "arraybuffer";**
```
var req = new XMLHttpRequest();
req.open("GET", "http://...", true);
req.responseType = "arraybuffer";
req.onreadystatechange = function () {
    if (req.readyState === 4 && req.status === 200){
        XlsxPopulate.fromDataAsync(req.response)
            .then(function (workbook) {
                // ...
            });
    }
};

req.send();
```
