### ISSUE TITLE
Uglify unable to transpile es6

### ISSUE THREAD

**Issue by benjaminlees** [dtjohnson/xlsx-populate#75]
Currently uglify does not work on `es6` modules. As xlsx-populate is a `es6` module I am getting the following error:

```
ERROR in vendor.ecffbc82141535281d22.bundle.js from UglifyJs
Unexpected token: name (XlsxPopulate) [vendor.ecffbc82141535281d22.bundle.js:18318,6]
```

To solve this issue I have used babel to transpile the code and have temporarily put the module in my src folder. Is anyone planning on turning this module to an `es5` module?

I would be happy to do it and make a pr if not.

**Comment by dtjohnson** [comment]
The version in the browser folder is a babel transpiled/browesified/uglified version. Does that not work for you?

**Comment by benjaminlees** [comment]
@dtjohnson yes that works, thanks.
