### ISSUE TITLE
Cannot read property 'cell' of undefined

### ISSUE THREAD

**Issue by 271bibi** [dtjohnson/xlsx-populate#77]
Hi, can somebody tell me why I can't access this cell? Thanks!

My Error: 
(node:2844) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'cell' of undefined

My Code:
`const XlsxPopulate = require('xlsx-populate');

// Load an existing workbook
XlsxPopulate.fromFileAsync("./test.xlsx")
    .then(workbook => {
        // Modify the workbook.
        workbook.sheet("Sheet2").cell("B3").value("Test!");
		 // Write to file.
        return workbook.toFileAsync("./out.xlsx");
    });`

**Comment by dtjohnson** [comment]
That indicates to me that it wasn't able to find a sheet named "Sheet2". Does your workbook have one?

**Comment by 271bibi** [comment]
Yes it does.. the whole purpose of this little experiment was to get access to a different sheet. If I want to change a cell on the first sheet, it works just fine.

**Comment by dtjohnson** [comment]
If you could provide your workbook I could look at it.
