### ISSUE TITLE
"numberFormat" style ignored

### ISSUE THREAD

**Issue by jampy** [dtjohnson/xlsx-populate#78]
I just started using `xlsx-populate` (awesome API, by the way!) and am unsing it in the browser.

All things work so far, except that the `numberFormat` style is being ignored. I'm using the format can be found in the docs, for testing:

```javascript
let val = new Date(); 
let cell = sheet.row(rowIdx + 2).cell(colIdx + 1);
cell.value(val);
cell.style("numberFormat", "dddd, mmmm dd, yyyy");
```

Displayed in *Libre Office* I only get the numeric date:

![image](https://user-images.githubusercontent.com/820758/29720804-56204638-89bb-11e7-87dd-1d4e9271b965.png)

Same thing applies to currency cells that I tried to format as `cell.style("numberFormat", "0.00 €");`  - same problem (cols D and E in the screenshot).

I've attached the generated file: [test (37).xlsx](https://github.com/dtjohnson/xlsx-populate/files/1252273/test.37.xlsx)

I don't have the original MS Excel and can only test with **LibreOffice Calc 5.1.5.2** on a Windows 10 PC that uses **german** locale (if that matters).

Am I doing something wrong?

**Comment by jampy** [comment]
Just noticed that applying `cell.style("numberFormat", "dddd, mmmm dd, yyyy");` to any cell (even text cells) changes their display font from a sans-serif font to a serif font, despite Libreoffice reporting `Cambria` font for *all* cells. What is going on?

**Comment by jampy** [comment]
Ok, this seems to be LibreOffice related. 

Excel displays the file as intended:

![image](https://user-images.githubusercontent.com/820758/29823027-bdd8fd1e-8ccd-11e7-94b0-f00bc75593f4.png)

Still, could there be a slight `xls-populate` bug/incompatibility (or error on my side) that causes LibreOffice to display these cells incorrectly? Maybe Excel has better error handling or something?

**Comment by dtjohnson** [comment]
That could definitely be the case. To find out you'd have to look at the xl/styles.xml file that are produced by Excel and LibreOffice to see what the differences might be. To look at them simply rename the .xlsx files as .zip and unzip.

**Comment by jampy** [comment]
The file generated by xlsx-populate contains this:

![image](https://user-images.githubusercontent.com/820758/29825530-0644ea66-8cd5-11e7-8c89-04b1845b131a.png)

I'm not familiar with the file format, but this looks like the format I'm setting in the lib.

When I save the file as a copy with Libreoffice, I get this:

![image](https://user-images.githubusercontent.com/820758/29825582-2659a418-8cd5-11e7-8f91-e719da5974c0.png)

Here is the file:

[test.37-libreoffice.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1260564/test.37-libreoffice.xlsx)

I can't do the same test with Excel because I have no licence (only a Excel Viewer).

Hope this gives you some hints....

**Comment by alandoyle95** [comment]
[test.38.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1261444/test.38.xlsx)

downloaded your generated file and saved as with excel 2013

**Comment by dtjohnson** [comment]
As Alan shows, it looks like the difference is that when you set this number format in Excel it adds backslashes before the commas and spaces. xlsx-populate doesn't do that. I'm willing to bet that if you set the style with `dddd\,\ mmmm\ dd\,\ yyyy` that it will work properly in LibreOffice. Note you'll need to double up the backslashes when setting:
```js
cell.style("numberFormat", "dddd\\,\\ mmmm\\ dd\\,\\ yyyy");
```

I'm guessing there is some format escape behavior that we're missing. I did some Googling but didn't find anything. If anyone can find some docs on the proper behavior that would be most helpful!

**Comment by alandoyle95** [comment]
I'll poke around :P

**Comment by jampy** [comment]
>  I'm willing to bet that if you set the style with dddd\,\ mmmm\ dd\,\ yyyy that it will work properly in LibreOffice. 

I tried with...

![image](https://user-images.githubusercontent.com/820758/29866491-d7e9638c-8d78-11e7-87fd-2266d6557939.png)

Looks fine in Excel 2016 viewer (but stops using my german system date settings and uses english slashes instead) - but still shows the number in LibreOffice :-(

**Comment by alandoyle95** [comment]
I'll mess around with Libra when I get to work and figure out how it stores
dates I'm interested in fixing this.. haha I use Libra office every day but
everyone else in my company uses office

**Comment by jampy** [comment]
Could it be related to the `count` attributes that are missing in the files generated by xlsx-populate?

I tried to manually patch the xlsx file by changing the node to `<numFmts count="2">` but it did not help.

---

FYI, I have another web-generated xlsx file here that is being displayed *correctly* by LibreOffice. It begins with...

```xls
<?xml version="1.0" encoding="UTF-8" standalone="true"?>
<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
    <numFmts count="6">
        <numFmt formatCode="dd.MM.yyyy HH:mm" numFmtId="164"/>
        <numFmt formatCode="#" m²"" numFmtId="165"/>
        <numFmt formatCode="0.00" t/ha"" numFmtId="166"/>
        <numFmt formatCode="0.00000000" "" numFmtId="167"/>
        <numFmt formatCode="0.00000000" Dispenser"" numFmtId="168"/>
        <numFmt formatCode="#" Stunde(n)"" numFmtId="169"/>
    </numFmts>
    <fonts count="2">
        <font>
            <sz val="10"/>
            <name val="Arial"/>
        </font>
        <font>
            <b/>
            <sz val="10"/>
            <name val="Arial"/>
        </font>
    </fonts>
...
```

**Comment by alandoyle95** [comment]
the count is only due to how xlsx-populate puts the data back into XML so that should not affect anything..

here is a working Libra office format for the date you wanted..

its interesting how it stores the date as a number and not a decimal.. 

![xlsx data](https://user-images.githubusercontent.com/6220497/29882139-01458520-8d61-11e7-83e2-b6bb72f8e3dd.png)
![xlsx data 2](https://user-images.githubusercontent.com/6220497/29882138-014004d8-8d61-11e7-8eb8-a85b4ed29e10.png)

**Comment by alandoyle95** [comment]
OK, so i figured it out.. now i will go try to figure out if its xlsx-populate that is causing it or not..

the reason its not formatting from your original test file was 2 reasons.. one causing the second.

your `numFmts` was missing the format style

`<numFmt numFmtId="165" formatCode="MMMM\ D", "YYYY">`
that is directly out of Libra office after formatting a single cell on a blank workbook, no idea why the line breaks into 2 "" blocks.

the second reason is each cell has...
`s="0"` 
so that was saying that the style was only General due to your General format being the first one. and not having the second Date format.

now off to code up a test script to see if i can see what xlsx-populate is doing

**Comment by jampy** [comment]
[out.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1264342/out.xlsx) shows no date formatting in LibreOffice Calc and Excel 2016 reports a file error and starts recovery. :-/

> the count is only due to how xlsx-populate puts the data back into XML so that should not affect anything..

just to avoid misunderstanding: it's *xls-populate* that is **not** adding the `count` attribute when generating the xlsx file. Maybe LibreOffice relies on these attributes (contrary to Excel itself)..?

**Comment by alandoyle95** [comment]
No xlsx-populate IS adding the count, excel and libra  don't even use count
as far as I know, the file error is due to the `NNNNMMMM` format

**Comment by dtjohnson** [comment]
@jampy, I'm wondering if this is a version issue? I just installed LibreOffice 5.4.0 and opened the original workbook you sent and it looked mostly fine. I also switched to the German locale and it still looks right:
![image](https://user-images.githubusercontent.com/218771/29901048-c5f8e7d8-8dc3-11e7-9efb-e4de31f02843.png)
The only weird thing is that it switches the font face...

The `count` attribute is probably not the issue. The counts are not required by the OOXML spec so we don't bother to emit them.

**Comment by jampy** [comment]
@dtjohnson you're right! I manually upgraded from LibreOffice 5.1.5.2 to LibreOffice 5.3.5.2 (the latest *stable*) and formatting works now as expected. :-)

Note that the internal "Update check" of the 5.1 version claimed that it was the most current version, so other users may also be stuck on a older version (Windows)...

> The count attribute is probably not the issue. The counts are not required by the OOXML spec so we don't bother to emit them.

Not by the spec, but perhaps by some implementations like older LibreOffice. It's just one difference I noticed and thought worth trying.

Anyway, I checked the release notes of Calc and found two mentions of numberFormat. Nothing related as it seems to me:
https://wiki.documentfoundation.org/ReleaseNotes/5.2#Number_Format
https://wiki.documentfoundation.org/ReleaseNotes/5.3#Number_Format

**Comment by alandoyle95** [comment]
does that update check thing for Ubuntu as well.
interesting... I will have to upgrade mine later this weekend!

**Comment by dtjohnson** [comment]
@jampy, I'm sure there is some subtle difference in how LibreOffice, Excel, and xlsx-populate handle the spec that was the original source of this. If anyone does figure out exactly the issue we're happy to support it, but I'll close this issue for now.

**Comment by erajanraja24** [comment]
Is there a way to get the style of any cell/Range?
