### ISSUE TITLE
corrupt files generated

### ISSUE THREAD

**Issue by shamier** [dtjohnson/xlsx-populate#8]
Firstly thank you for a great API.

I have some very basic node code that reads an xlsx template in successfully...modifies it and writes a file out.

The file however cannot be opened in excel, It seems to open fine in googles spreadhseet viewer and libreoffice however. I have tried many permutations of base64encoding the output and that has not helped either.

I have attached a file. 
[vertrans_template_139.xlsx](https://github.com/dtjohnson/xlsx-populate/files/428455/vertrans_template_139.xlsx)

Any assistance is appreciated.

**Comment by dtjohnson** [comment]
Sorry to hear about the trouble! Sometimes Excel will call a file corrupt if things are not exactly in the order it expects. Earlier versions of xlsx-populate had some bugs that would result in "corrupt" workbooks. Could you confirm which version you are using? Is there some sample code you can share?

**Comment by shamier** [comment]
Thank you for the incredibly swift reply.

I actually updated to the latest version ("version": "0.3.0",) and retested about a few hours ago.

WRT sample code I have for debugging simplified it to...

var workbook = Workbook.fromFileSync("./vertrans_template_139.xlsx");
workbook.toFileSync("./out.xlsx");

and then checked the output file.

I agree its very likely an excel issue and if there's nothing obvious I have missed then please close the issue.

Again. the api is really good. I have used two others to make the same edits to existing templates and both seem to lose a fair bit of formatting whereas this one does not.

**Comment by dtjohnson** [comment]
Odd. I'm not able to reproduce. I ran your code with the workbook you attached and the output opened just fine... I'm using Excel 2013. What version do you have?

**Comment by shamier** [comment]
I am using excel 2010. Others have experienced the same issue as well, I am certain its just an excel or possibly OS funny regarding how files are being written out then.

Given the issue is purely my side I will close the issue though. Thank you for your assistance. Massively appreciated.
