### ISSUE TITLE
preserve comma in cell value

### ISSUE THREAD

**Issue by riv3n** [dtjohnson/xlsx-populate#81]
Is there a way to preserve the comma in the cell value? I have a port column that contain multiple ports separated by a comma; e.g. 80,443 becomes 80443.

**Comment by alandoyle95** [comment]
Number format with style

**Comment by riv3n** [comment]
Thank for replying. I tried applying the style to the whole column, but it appears to be unchanged:

` ws.column("D").style("numberFormat", "#,###");
    ws._rows.forEach(row => {
      let server = new Object();
      server['host'] = row._cells[1].value().trim();
      server['IPorMask'] = row._cells[2].value().trim();
      server['protocol'] = row._cells[3].value().trim();
      server['ports'] = row._cells[4].value();`

**Comment by riv3n** [comment]
Thank you for replying. I tried applying the style to the whole column, but it appears to be unchanged: https://gist.github.com/riv3n/e923104e2eec0aa325a6fcad7b14b549

**Comment by alandoyle95** [comment]
hmm.. then i suppose just try to  apply it to each cell first to make sure that its working.. i did test that #,### would do what you wanted. and it does.. at least on LibraOffice

**Comment by dtjohnson** [comment]
Looks like you're parsing data from the workbook. What seems to be going on
is that the source data in the workbook is stored as a number, not a
string. The comma you see is just Excel formatting. All that gets stored in
the workbook is the raw number and a format code. Can you change the source
workbook to use a string value?

**Comment by riv3n** [comment]
Thank you. I changed the source data to a string.
