### ISSUE TITLE
How to use FormulaError class related methods

### ISSUE THREAD

**Issue by duvemula** [dtjohnson/xlsx-populate#82]
Hi @dtjohnson,

While reading data from workbook I am getting FormulaError { _error: '#N/A' }. I am unable to use FromulaError class methods.

Would mind could you please give some examples for FormulaError class method usage.

Regards,
Durga Prasad

**Comment by dtjohnson** [comment]
There is only one method: `error` that returns the error code. Otherwise the errors are just singletons you can compare to the statics.
