### ISSUE TITLE
Workbook returning hidden row values

### ISSUE THREAD

**Issue by duvemula** [dtjohnson/xlsx-populate#83]
Hi @dtjohnson,
I observed that workbook returning hidden row values i.e returning collapsed row child row values.

Could you please take a look.

Regards,
Durga Prasad
[Example With Grouping - Report Grouping.xlsx](https://github.com/dtjohnson/xlsx-populate/files/1309880/Example.With.Grouping.-.Report.Grouping.xlsx)

**Comment by alandoyle95** [comment]
Are you trying to look though data?
If so you can add a check if it's hidden and then `continue;`

But it is not designed to return only what's shown

**Comment by duvemula** [comment]
Thanks @alandoyle95.
is there any way to get all rows from workbook like WorkbookRef.sheetname.rows().

Regards,
Durga Prasad

**Comment by duvemula** [comment]
Hi @alandoyle95,
Does xlsx-populate support .xlsb format?

Regards,
Durga Prasad

**Comment by alandoyle95** [comment]
no it does not support that file format.. but maybe some day

**Comment by dtjohnson** [comment]
Yeah, I don't think XLSB will ever happen.
