### ISSUE TITLE
Hide just a cell

### ISSUE THREAD

**Issue by FraVieMor** [dtjohnson/xlsx-populate#85]
Is there any way to hide just a cell with xlsx-populate??

I know it is possible for rows/columns but i need to hide just a cell.

Thanks!

**Comment by dtjohnson** [comment]
Can you actually do that in Excel? If you can't do it in Excel you can't do it in xlsx-populate.

**Comment by FraVieMor** [comment]
Yes, i can: https://support.office.com/en-us/article/Hide-or-display-cell-values-c94b3493-7762-4a53-8461-fb5cd9f05c33

**Comment by alandoyle95** [comment]
that should be able to be done with `cell.numberFormat(';;;;')`

**Comment by FraVieMor** [comment]
I finally do with `cell.style({ numberFormat: ';;;'})`.
Thanks!
