### ISSUE TITLE
Number stored as Text with percentage

### ISSUE THREAD

**Issue by Tonio31** [dtjohnson/xlsx-populate#86]
Hello,

I love your library, it is awesome and documentation is great.

However, I have a small issue with percentage.

I have the following code to add a cell:
```
ioSheet.cell( 'A1' )
    .value( '10%' );
```

When I open the excel file after it is generated, we can see a small green triangle (meaning excel is trying to tell you something is wrong) and it says "Number stored as Text".

I guess it makes sense because this could be a number and just have a formatting in excel that will add the %.

I see two possible solutions but don't know how I can achieve neither of them:
 1) Forcing Excel to consider this value as string (not sure it is possible)
 2) removing the %, send a number to Excel and format the cell as percentage.

To do 2), I've seen the option numberFormat, so I tried to add this (as reference [here](https://support.office.com/en-us/article/Number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68?ui=en-US&rs=en-US&ad=US)):
```
ioSheet.cell( 'A1' )
    .value( 10 )
    .style({
        numberFormat: '%'
    });
```

But it doesn't work, I have only a % in the cell in Excel.

I must do something wrong as it seems you guys planned for this feature but I can't figure out how to do that.

**Comment by dtjohnson** [comment]
Setting the value with the string '10%' puts a string value in the cell. This is correct behavior.

Your 2nd option is the right approach, but your number format is wrong. It should be '0%'. You can see this in Excel if you format a cell as percent, open the number format window for the cell, and switch to the "Custom" page. The highlighted format is what you want.

**Comment by Tonio31** [comment]
It is working perfectly using the cell format '0%' instead of '%', 

Thanks a lot for your help
