### ISSUE TITLE
Duplicate/add rows with same template

### ISSUE THREAD

**Issue by fabripeco** [dtjohnson/xlsx-populate#9]
Hi,
I would like to propose a possible enhancement. It would be fine to duplicate a row with a given template by adding the same row in the following rows. Is it already possible in some way? Is there something similar in your roadmap?

Thank you for your work!

**Comment by dtjohnson** [comment]
Sorry, I'm not sure I understand. Could you explain a little more what you are looking for?

**Comment by fabripeco** [comment]
My idea was to duplicate row 3 (e.g.), with its template, formula, style and so on, copy it to row 4 by adding a row in the sheet and then populate its cells with different values. Maybe it isn't possible. Sorry for my english

**Comment by dtjohnson** [comment]
Yeah, unfortunately that's not possible with the API as it is now. There is no support for styling. What you could do instead is style all of your rows in your template beforehand (even without content in them). Then populate the values.
