### ISSUE TITLE
Reading big size files crash the app.

### ISSUE THREAD

**Issue by juanpiterson** [dtjohnson/xlsx-populate#91]
Hello,
First i have to said that this library is amazing. It's working very well for me, solving many problems that i had with other products. Thanks you guys for your work.

My problems is that i'm trying to read big size xlsx file, (about 200 000 row) and my nodejs app crash, is there a limit of how many row the library can handle when using the fromFileAsync function?

Maybe is there a way for reading the file in batches?
Can i read some file information (metadata, sheet names, etc) without actually read the cells data.

thanks you in advance.

**Comment by dtjohnson** [comment]
It's limited to about 10 million cells. See https://github.com/dtjohnson/xlsx-populate/issues/18. I don't think there is much more we can do to lift that limit at the moment. There are options for only loading certain sheets though. You can also try increasing Node's memory limit with the --max_old_space_size option.

**Comment by alandoyle95** [comment]
maybe we should implement a `rangeToArray`

**Comment by juanpiterson** [comment]
Hello @alandoyle95, my problem it's from the first moment when i try to read the file.
Can i use the 'rangeToArray' approach without read the entire file?

**Comment by alandoyle95** [comment]
probably not, but there may be a way... just haven't looked

**Comment by jbrecht** [comment]
since XLSX files are actually ZIP containers, doing a streaming read would be pretty tricky.

**Comment by dtjohnson** [comment]
Yep. Zip read streams don't really work given the file structure. Furthermore, it's a zip of XML files that contain referential data. I'm sure it's possible to extract data from huge workbooks, but that's not the purpose of xlsx-populate. I could be wrong, but I think we've squeezed about as much juice out of the performance as is. The fundamental problem is that with a sheet of 200k rows you have a massive XML document, which is a pain to manipulate.

**Comment by alandoyle95** [comment]
Yea at that point with that much data it should be in a different format
for looking at

**Comment by anishbishnoi127** [comment]
my node app crash when do           **await workbook.toFileAsync(tempStoreFile);**
its load all in the memory of ram and it's crashing my app. any other way to load instead of memory load in ssd or hdd ?
