### ISSUE TITLE
Workbook.fromFileAsync is not supported in the browser

### ISSUE THREAD

**Issue by remcenit** [dtjohnson/xlsx-populate#94]
I'm trying to use the library in my Angular 2 project. I added it to my systemjs.config file and mapped it: `'xlsx-populate': 'npm:xlsx-populate/browser/xlsx-populate.js',` I tried to read an excel file from one of the project folder and add data to it. But it returns this error. 

> ERROR Error: Workbook.fromFileAsync is not supported in the browser
    at Function.value (Workbook.js:75)
    at Function.value (XlsxPopulate.js:45)
    at ProjectComponent.downloadFile (project.component.ts:60)

**Comment by dtjohnson** [comment]
Yes, the filesystem API is only supported in Node. You'll need to read in files by AJAX, a file input, etc. There is an example of browser usage in the examples folder.

**Comment by remcenit** [comment]
Hey sorry, I'm a newbie. So I can't use this inside my typescript file? 
```
getFileValue(): void {
const XlsxPopulate = require('xlsx-populate');

XlsxPopulate.fromFileAsync("./app/Shared/Files/Template_Sample.xlsx")
    .then(workbook => {
        // Modify the workbook.
        const value = workbook.sheet("Sheet1").cell("A1").value();
        
        // Log the value.
        console.log(value);
    });
}
```

**Comment by alandoyle95** [comment]
Here is the link to the example file @dtjohnson  was talking about, it looks like you are not loading the file correctly.

`https://github.com/dtjohnson/xlsx-populate/blob/master/examples/browser/index.html`
